### ISSUE TITLE
1.2.1 - Making a list of repositories and modules

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#10]
## `@todo`
- [x] all dat related repos and modules
  - [x] find all relevant dat repositories (code, organization docs, documentation, tutorials, design...)
  - [x] find all different language implementations
  - [x] find all npm modules
  - `@output` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from [`comment`](https://github.com/dat-ecosystem/organization/issues/10#issuecomment-999071596)
    - next #11 
    - next #12
    - next #13
    - next #15
    - next #16

---

## `@info`

| type        | estimation        |
| ------------ | ------------------- |
| deadline  | 2022.01.31      |
| duration   |  `4 hours`        |
| bounty     | `$160 USD`     |
| assignee  | @ninabreznik |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2022.01.31`
     * budget: `40 USD / hour`
     * duration: `4 hours`
* review:
    * date: `2022.01.25`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2022.02.13`
    * sender: @dat-ecosystem/consortium 
    * receipient: @ninabreznik 
    * amount: `160 USD`

**Comment by ninabreznik** [comment]
**worklog `2022.12.21`**
- `@output` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules)
