### ISSUE TITLE
dat-ecosystem website_course_card

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#102]
#70

## `todo`

- [x] Move the course card to figma component
   - `@input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037) from #71 
   - [x] card header 
      - [x] add date with calendar icon
      - [x] add time with clock icon
   - [x] Title with leading icon
   - [X] descrption
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`course_card_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=961%3A4423&t=YAjl5us7XogR87I0-4) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks

- Move the course card to figma component   - `7min`
   - card header
      - add date with calendar icon
      - add time with clock icon
   - Title with leading icon
   - descrption
   - create and update tasks, worklog, comment etc - `6min`
   - `@output` 📦 [course_card_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=961%3A4423&t=YAjl5us7XogR87I0-4)
---

### worklog

---

### feedback

---

### proposals
