### ISSUE TITLE
Pico stack - demo/review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#103]
#18

## `@todo`
 `@input`: video interview :question:
 - [ ] learn about the project (if you can't find all the info online, interview the core contributors)
 - [ ] record a screencast (a demo) with the author or just yourself
 - [ ] write a short blog post in a markdown
  * a bit about yourself (to understand from which perspective are the interviews/demos/article)
  * short about the project ( 1 paragraph)
  * main links (website, documentation, code, community/discord etc.)
  * video interview link
  * demo screencast link
 - [ ] publish video to youtube
 `@output` :question:  `A 1 page write up with the link to the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/ByS7hlW0i

**Comment by ninabreznik** [comment]
Thanks @KaylaOlu. Since we will be publishing these interviews over next few months, can I please ask you to not delete your HackMDs, so we can access the texts. 

Alternatively, you could copy and paste them here in the comment. Maybe that would actually be best and then we know they are here and you can you whatever you want with your hackmd documents.

So, could you please copy paste the text for all the interviewees in the comments of the issue for that particular project (here for Pico, Ahau under Ahau issue etc.)

Thank you very much in advance :)

**Comment by KaylaOlu** [comment]
Interview
https://we.tl/t-IIPNpTwE6t

**Comment by KaylaOlu** [comment]
> Thanks @KaylaOlu. Since we will be publishing these interviews over next few months, can I please ask you to not delete your HackMDs, so we can access the texts.
> 
> Alternatively, you could copy and paste them here in the comment. Maybe that would actually be best and then we know they are here and you can you whatever you want with your hackmd documents.
> 
> So, could you please copy paste the text for all the interviewees in the comments of the issue for that particular project (here for Pico, Ahau under Ahau issue etc.)
> 
> Thank you very much in advance :)

oh it's fine, I won't be deleting the hackmd file because I only opened it for this purpose as I don't use it for any thing else.

**Comment by ninabreznik** [comment]
Hey, I downloaded the video and it seems the sound is better now but sadly there are some issues left.

1. In 4:38 there is a very loud background noise that lasts for almost 10s. This one is really horrible. We have to find a fix for this.
2. In 8:02 you are talking but there is a background noise the whole time, so, I think I mentioned before already, that we could just cut this whole part out.
3. Also, let's cut from 13:06 to 13:29
3.  I don't know if you use fade-in & fade-out effects. I use both when I make transitions between two videos (one fades out and another fades in) as it makes the transitions feel way smoother. All the transitions in the first minute would benefit from it.
4. Additionally, in some parts could even have a bit longer transitions, to make the video look less jumpy, for example:

- min 0:12 (you can also fade out the audio there)
- min 0:24

---

In min 3:40 he doesn't finish the sentence. He says: 'It is more for advance users, I (would say)', but the last part is cut. So, either try to cut before he says 'I would say' or leave him finish the sentence.
When you cut in the middle of the sentence, I think it is important to use the audio fade-out and fade-in so that also audio cuts feel smooth.

---

**Comment by KaylaOlu** [comment]
Interview and Demo
https://we.tl/t-jXubbqnJ2e
