### ISSUE TITLE
dat-ecosystem website_container

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#104]
#70

### `todo`
- [x] design website_container_v0.0.1
   - `@input` [terminal_frame_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1084%3A2644&t=cnN6e9EzdGiUbbKm-4) from #86 
   - [x] make pixel art social platform icons
   - [x] add social links container 
   - [x] create an issue, add and update task, upload worklog
   - `@output` [`website_container_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1068%3A7138&t=cnN6e9EzdGiUbbKm-4) from [comment](https://github.com/dat-ecosystem/organization/issues/104#issuecomment-1440936889)

---

- [x] update website_container_v0.0.2 - `11min`
   - `@input` [terminal_frame_v0.0.4](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1100%3A1922&t=ZQIChIVClj4gT04y-4) from #86 
   - [x] read feedback - `7min`
   - [x] move the navbar to top
   - [x] add social links container 
   - [x] create an issue, add and update task, upload worklog - `
   - `@output` [`website_container_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1102%3A2273&t=ZQIChIVClj4gT04y-4) from [comment](https://github.com/dat-ecosystem/organization/issues/104#issuecomment-1445484455)

**Comment by Mehrabbruno** [comment]
### tasks

- design website_container_v0.0.1
   - make pixel art social platform icons - `1h32min`
   - add social links container - `38min`
   - create an issue, add and update task, upload worklog - `18min`
   - `@output` [website_container_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1068%3A7138&t=cnN6e9EzdGiUbbKm-4)

---

###  worklog

[worklog-114](https://youtu.be/T_CssheDXMY)

--- 

### feedback

--- 

### proposals

**Comment by serapath** [comment]
**feedback `2023.02.23`**

![screen](https://imgur.com/psG9lwg.png)
love it. no color change. texture is great too. icons cool too :-)
also the "grey on grey" feels more retro for the window backgrounds.


**given all that** - it really does resemble datdot a lot now layout wise.
good so we might re-use implementation for datdot with changed theme,
but for dat-ecosystem => lets keep it, but the menu bar on top to differentiate

![screen2](https://i.imgur.com/Qrv02Om.png)
I think it would be ok if that page was scrollable (even desktops dont do that)
=> the right green monitor frame line could double as a "scroll bar"  

The icons on the desktop and/or the windows don't have to be moveable.
No resize or move for icons or windows for now
* => [x] close button navigaes to "home"
* => [[]] maximizes, ok we have that in datdot too
* => [-] minimizes into desktop icon


Regarding the scrollbar, we can either write our own custom scrollbar component
Or we stle the existing, there are many codepens showing how to do it natively.
e.g. even win95 css scrollbars exist.

...anyway, that's for implementation, the way it looks now is great.

---

**otherwise: a few minor changes:**
1. each menu bar button (e.g. home, projets, ....)
  * => should switch the content area just like a vscode tab
  * if a content area needs scrolling, it can start out with a window "maximized"
2. let's keep the socials in the menu bar (we still deal with a website)
  * socials should also include the cabal icon link
3. let's add a "social button sized" terminal button to expand/collapse
  * toggle => terminal should slide in/out from below (like browser devtools)
  * position the terminal icon maybe after socials or before dat-ecosystem logo


Otherwise let's keep moving as fast as we can towards implementation :-)

**Comment by Mehrabbruno** [comment]
### tasks

- update website_container_v0.0.2 - `11min`
   - read feedback - `7min`
   - move the navbar to top
   - add social links container
   - create an issue, add and update task, upload worklog - `27min`
   - `@output` [website_container_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1102%3A2273&t=ZQIChIVClj4gT04y-4)

---

### worklog

[worklog-115](https://youtu.be/ZJA2ujGPlUI)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2023.02.27`**

The terminal icon is great in purple.
The social buttons might be fine in mobile when there is not much space, but could we keep them expanded on tablet/desktop when there is enough space, so people who come to the page can immediately click them. (also cabal chat icon is still missing from it)
We will try to reduce socials in the future and not make more of them.
If we ever end up with more, we will probably combine the approach and have the most important ones shown directly and another "more" button (like you made now) to show the remaining socials.
![navbar](https://imgur.com/6WIV7dO.png)

But you have that designed, so let's make it fixed so we have components and can move to implementation i guess.
