### ISSUE TITLE
UI CSS library implementation

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#106]
#37

## `@todo`
* [ ] research many retro operating systems and images for inspirations
  * [ ] go through comment and linked documents below to add more tasks
* [ ] turn everything into vanillaJS CSS theme components

**Comment by serapath** [comment]
**feedback `2023.03.09`**

**This is for the implementation phase of our themes**

Implementation should aim for at least 3 things:
1. cherry pick best "retro **UX** features", but back-porting them into retro 70s/80s **UI**
    * best UX without compromising 1970s/1980s retr UI 
2. using tech json/css/javascript/html/markdown and tools/usecases from now
3. retro in terms of dither, pixelated, monochrome like late 70s early 80s (more below)

---

Can we plan and implement a CSS UI library?

Maybe even two, to ensure we can apply not just a light and dark theme, but a different one,
and that our components are generally easily re-usable and themable.
1. The main theme should be a dat garden retro style ancient 1970s/80s theme.
2. The second one could fall more into windows95 or super nintendo style.


## [>click<](https://www.youtube.com/watch?v=5uaYHYs4ubw)
[![commodore](https://imgur.com/SNeuYjx.png)](https://www.youtube.com/watch?v=5uaYHYs4ubw)
An old commercial video for the commodore 64, the most sold computer system of all time

------------------------------------------------------------

### css theme
some css libraries that enable the style of a certain retro system
##### examples
* https://nostalgic-css.github.io/NES.css/
* https://github.com/vinibiavatti1/TuiCss
  * https://github.com/vinibiavatti1/TuiCss/wiki/Showcase
* https://alexbsoft.github.io/win95.css/
* https://demo.themesberg.com/windows-95-ui-kit/
* https://botoxparty.github.io/XP.css/
* https://jdan.github.io/98.css/

##### css reset ides
* https://www.resset.dev/docs/#features
* https://github.com/jgthms/minireset.css/blob/master/minireset.css
* https://elad.medium.com/the-new-css-reset-53f41f13282e

can we have a radical and minimal css reset (maybe not as radical as below)
```css
:root { all: unset; } *:after, *:before { all: inherit; }
```
and then implement on top of that a css ui library for all our desktop elements?
* e.g. icons, windows, scrollbars, etc...

First, all the regular html tags to have a baseline that can be used standalone.
Then all the more advanced components we need as part of our css desktop ui library.


---

# elements
I list a vast variety of screenshots, but the point is to pick specific visual elements or aspects from each of those so we can combine them. So for most screenshots, the majority of content should be ignored and just the specific parts i describe should be considered for inspiration.

I think in "retro" designs, things are often very "explicit".
I would like to focus on minimalism, but not lose the retro explicitness.


*In all the links to documents below, please ignore almost everything in the screenshots and focus only on the specific aspects of the screenshot, based on the text and title of the linked documents.*

1. [how to drag/resize borders](https://hackmd.io/oqDE3OrKR3yx8EcbaZU7OQ)
2. [window, title bar, with window icons (e.g. minimize/maximize/close/...)](https://hackmd.io/3tBFcg61SQG39rcUEPZePw)
3. [contrast, dither, colors, gradients, etc...](https://hackmd.io/4OApQs1eS4WRAR0IlM9kLA)
4. [window border/borderless & transparency](https://hackmd.io/OHI9bR4bRRCSyZA_RWWTJg)
5. [icons](https://hackmd.io/_I0ar9Z3T82DmFj_ofMBDQ)
6. [popups/overlay](https://hackmd.io/WpIT2qi5QryaHjj05e20Rw)
7. [status bar](https://hackmd.io/kF6fvCbJSU6Eh-zKm0fBNw)
8. [context menus](https://hackmd.io/kF6fvCbJSU6Eh-zKm0fBNw)
9. [shell](https://hackmd.io/YqzvUnS6RlWuugQ-NLNFYw)
10. [programs](https://hackmd.io/6UmEpKYWTOmxW64TWtFV4Q)
11. [tiling window manager](https://hackmd.io/PrqsUCrCQFijNEzRpIEGJw)


---

# retro systems (for inspiration)
There are specifically six retro desktop systems i would love to take inspiration from,
maybe even add future themes for those in general and those are:

1. [suntools](https://www.google.com/search?q=suntools&tbm=isch&ved=2ahUKEwjH5IqmuND9AhXTsEwKHfjGA0cQ2-cCegQIABAA&oq=suntools&gs_lcp=CgNpbWcQAzIFCAAQgAQyBwgAEIAEEBgyBwgAEIAEEBg6BAgAEEM6CAgAEIAEELEDOggIABCxAxCDAToGCAAQBRAeOgkIABCABBAKEBhQnQdYpRBgiRFoAHAAeACAAVqIAZ8EkgEBOZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=nKYKZMemA9PhsgL4jY-4BA&bih=1135&biw=2194)
2. [perq System](https://www.google.com/search?q=perq+operating+system&tbm=isch&ved=2ahUKEwixpqGyuND9AhUsbKQEHUA1DjcQ2-cCegQIABAA&oq=perq+operating+system&gs_lcp=CgNpbWcQAzoHCAAQgAQQGFDsB1j2EWDbEmgAcAB4AIABQogBhgeSAQIxN5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=taYKZPH3I6zYkdUPwOq4uAM&bih=1135&biw=2194)
3. [visi on visicorp](https://www.google.com/search?q=visi+on+visicorp&tbm=isch&ved=2ahUKEwjP5_G3uND9AhVHpicCHTUODNIQ2-cCegQIABAA&oq=visi+on+visicorp&gs_lcp=CgNpbWcQAzoFCAAQgAQ6CAgAEIAEELEDOgQIABBDOgQIABADOgcIABCxAxBDOgYIABAFEB46BggAEAgQHjoHCAAQgAQQGDoJCAAQgAQQChAYUNbLAlj14gJg_uMCaAFwAHgAgAGgAYgBpQmSAQQxNy4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=waYKZI-DGMfMnsEPtZywkA0&bih=1135&biw=2194)
4. [tandy deskmate](https://www.google.com/search?q=tandy+deskmate&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjV0qOqt9D9AhXRYcAKHVOICSgQ_AUoAXoECAEQAw&cshid=1678419499481543&biw=2194&bih=1135&dpr=1.75)
5. [at&t unix pc](https://www.google.com/search?q=at%26t+unix&tbm=isch&ved=2ahUKEwj_gsLgt9D9AhWFmycCHXFOD1EQ2-cCegQIABAA&oq=at%26t+unix&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMggIABAIEAcQHjIHCAAQgAQQGDIHCAAQgAQQGDIHCAAQgAQQGDIHCAAQgAQQGDIHCAAQgAQQGDoGCAAQCBAeUN8EWOUHYPwIaABwAHgAgAGZAogB2wSSAQUxLjAuMpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=CqYKZP_VCYW3nsEP8Zy9iAU&bih=1135&biw=2194)
6. [c64 geos](https://www.google.com/search?q=c64+geos&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwid2M_Ot9D9AhWWFMAKHTzkBvEQ_AUoAXoECAEQAw&biw=2194&bih=1135&dpr=1.75)
