### ISSUE TITLE
Future ideas / Backlog

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#107]
#115

## `@todo`
- [ ] create a fund on Open Collective (collect funds so projects in the ecosystem can apply for funding from our own fund)
  -  see some existing funds https://opencollective.com/search?q=&type=FUND&offset=20
- [ ] make protocols.dat-ecosystem.org and list all the protocols in the ecosystem
  - hypercore, cable, earthstar, ssc's (no name yet) ...
- [ ] make bounties for important tasks
  - bridging communication channels (gitter, discord, cabal...)
