### ISSUE TITLE
dat-ecosystem website_scrollbar

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#108]
#70

## `@todo`

- [x] design a scroll bar
   - [x] design horizontal and vertical scrollbars in retro ui
   - [x] create and update tasks, worklog, comment etc
   - `@output` 📦 [`scrollbar_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1360-6666&t=Ox51Ohm1m5cMB0nq-4) from [comment](https://github.com/dat-ecosystem/organization/issues/108#issuecomment-1500707178)

---

- [x] update scrollbar_v0.0.1
   - [x] update the arrow btn design
   - [x] create and update tasks, worklog, comment etc
   - `@output` 📦 [`scrollbar_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1360-7963&t=Ox51Ohm1m5cMB0nq-4) from [comment](https://github.com/dat-ecosystem/organization/issues/108#issuecomment-1500707178)

**Comment by Mehrabbruno** [comment]
### tasks - `2023.04.08`

- design a scroll bar - `26min`
   - design horizontal and vertical scrollbars in retro ui
   - create and update tasks, worklog etc
   - `@output` 📦 [`buttons_v0.01`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1360-6666&t=Ox51Ohm1m5cMB0nq-4)

- update scrollbar_v0.0.1 - `5min` 
   - update the arrow btn design
   - create and update tasks, worklog, comment etc - `15min`
   - `@output` 📦 [`buttons_v0.02`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1360-7963&t=Ox51Ohm1m5cMB0nq-4)

---

## worklog 

[worklog-131](https://youtu.be/BDx_oaC_XfY)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.04.09`**

great. buttons are cool. nice and retro.

the scrollbar arrow icons should probably be the "small" icon, whilethe other icons are the "medium icons" and maybe the dat logo is the "large icon".

anyway, ideally they are somehow multiple of each other, so maybe we cant use 3 icon sizes but just two - multiples of each other to stay in our "grid" metaphor which we should try to also stick to when we implement things and resize/or drag thing around, that nothing moves but instead things snap into from grid square to grid square if that makes sense.
