### ISSUE TITLE
1.3.1 - Transitioning repos to Dat-ecosystem

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#11]
## `@todo`
- [x] transition repos under Dat ecosystem Github & NPM to have all repos and modules under dat-ecosystem
  - `@input` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from #10 
  - [x] move all repos under dat ecosystem org (npm & github)
  - [x] reach out to the dat contributors (based on the list)
  - [x] figure maintainance status (info which project is still maintained and which not)
  - [x] ask maintainer about the successor for the unmaintained projects 
  - [x] make #5 
  - [x] make dat-ecosystem-archive github org https://github.com/dat-ecosystem-archive
  - [x] update list with maintainance status + new links to the repos and modules (under dat-ecosystem org) + successor (if exists)
  - [x] Make Dat-Ecosystem_Archive repo
  - [x] Transfer all repos there
  - [x] Add deprecation notice (make a template) to repos ABOUT and README
  - [x] Add deprecation notice to websited (make a template)
  - [x] See if any repo has a successor and link to that (how to find out? Ask community - consortium & co)
  - [x] transition deprecated/abandoned modules to (`dat-ecosystem` npm org)
  - `@output` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem) from [`comment`](https://github.com/dat-ecosystem/organization/issues/11#issuecomment-1002328083)
    - next #12
    - next #13
    - next #15
    - next #16
  - `@output` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive) from [`comment`](https://github.com/dat-ecosystem/organization/issues/11#issuecomment-1002328083)
    - next #12
    - next #13
    - next #15
    - next #16

---

## `@info`

| type        | estimation        |
| ------------ | ------------------- |
| deadline  | 2022.01.31      |
| duration   |  `8 hours`        |
| bounty     | `$320 USD`     |
| assignee  | @ninabreznik |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2022.01.31`
     * budget: `40 USD / hour`
     * duration: `8 hours`
* review:
    * date: `2022.01.25`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2022.02.13`
    * sender: @dat-ecosystem/consortium 
    * receipient: @ninabreznik 
    * amount: `320 USD`

**Comment by ninabreznik** [comment]
**worklog `2021.12.29`**
- `@output` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem)
- `@output` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive)
