### ISSUE TITLE
tidy up the logotype

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#114]
#37 

## `@todo`
* [x] tidy up logotype
  * [x] make logo work with the webpage
  * [x] make it work as a discord avatar
  * [x] make it work as a twitter avatar
  * [x] make it work as a github avatar
  * `@output` :package: [`refined logotype versions`](https://github.com/dat-ecosystem/organization/tree/main/media/assets%20by%20tommings/logo) from https://github.com/dat-ecosystem/organization/issues/114#issuecomment-1581450559
    - next #37

**Comment by serapath** [comment]
## tasks
* [x] tidy up logotype
  * [x] make logo work with the webpage
  * [x] make it work as a discord avatar
  * [x] make it work as a twitter avatar
  * [x] make it work as a github avatar
  * `@output` :package: [`refined logotype versions`](https://github.com/dat-ecosystem/organization/tree/main/media/assets%20by%20tommings/logo)

## worklog

## feedback
- we have the first draft for the brand identity. Our friends at Vasic Media helped us form the concept which they described in the identity idea (see the link above). But the concept is very dry and corporate, so we need to make it cool now :smile_cat: 
- we want to communicate with a voice of a mad scientist character, example: Doc Emmet Brown (back to the future) Doc Banner (😅) , Doc Peter Vankman (ghostbusters), Rick (from Rick and Morty) 

## proposals
