### ISSUE TITLE
Newsletter setup

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#117]
## `@TODO`
1. Newsletter setup

- `input`: https://github.com/dat-ecosystem/organization/issues/19
- [x] get the mailing list (Joe Hand / json) - Alex
- [x] setup new emailing service (Riseup) - Alex
  - research email service providers 
  - apply & correspond with Riseup for free email service
  - read documentation and configure the mailing list
  - process csv mailing list we got from Joe Hand and make it compatible with Riseup import
  - send test email
- [ ] import emails - Diego?
- [ ] create a template with new designs - Diego?
- [ ] send out 3 newsletters - Diego?
  - Dat Project Update 2023 https://github.com/dat-ecosystem/organization/issues/121
  - about the interview series - Diego?
  - about demos - Diego?
  - later 
    - a digest email every 3 months? See [Redecentralize emails](https://redecentralize.org/redigest/)
    - 10 years of dat (after the grant, we need more time for this one and Alex would like to write or direct the article https://github.com/dat-ecosystem/organization/issues/119
---
## `info`

Budget 
$ 500

**Comment by ninabreznik** [comment]
This Redecentralize newspaper was quite popular and I just met Gerben, who was last working on it and he told me, it is dead since 2022, so there is a gap in the dweb community that Dat ecosystem can fill with out newsletter re-launch
https://redecentralize.org/redigest/

**Comment by ninabreznik** [comment]
Next:
- https://github.com/dat-ecosystem/organization/issues/121
- https://github.com/dat-ecosystem/organization/issues/119
