### ISSUE TITLE
1.3.2 Archiving Repos

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#12]
## `@todo`
- [x] archive: add deprecation notice to unmaintained repositories & link to successor projects (if they exist) or to general tech overview
    - `@input` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from #10
  - `@input` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem) from #11
  - `@input` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive) from #11
  - [x] make deprecation note template
  - [x] add deprecation notice to all repos
  - [x] update github and npm
  - [x] make all repos/modules have a deprecation notice if outdated and/or have no maintainers
  - [x] include successor module/project link if applicable
  - [x] add a link to the official dat-ecosystem list of maintained modules
  - [x] link to new alternative (dat cli => hyp) if one exists
  * `@output` :package: [`all repos archived here`](https://github.com/dat-ecosystem-archive) from [`comment`](https://github.com/dat-ecosystem/organization/issues/12#issuecomment-1002327702)
  * `@output` :package: [`deprecation notice templates`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from [`comment (see below)`](https://github.com/dat-ecosystem/organization/issues/12#issuecomment-1002327702)

---

## `@info`

| type        | estimation        |
| ------------ | ------------------- |
| deadline  | 2022.01.31      |
| duration   |  `4 hours`        |
| bounty     | `$160 USD`     |
| assignee  | @ninabreznik |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2022.01.31`
     * budget: `40 USD / hour`
     * duration: `4 hours`
* review:
    * date: `2022.01.25`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2022.02.13`
    * sender: @dat-ecosystem/consortium 
    * receipient: @ninabreznik 
    * amount: `160 USD`

**Comment by ninabreznik** [comment]
**worklog `2022.01.25`**
  * `@output` :package: [`all repos archived here`](https://github.com/dat-ecosystem-archive)
  * `@output` :package: [`deprecation notice templates`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) (see below or at bottom of linked hackmd)



## Deprecation notice examples

https://dat-ecosystem-archive.github.io/website

### About section on Github:

[ DEPRECATED - see https://github.com/hyperswarm/dht for similar functionality. More info on active projects and modules at https://dat-ecosystem.org/ ] 

[ DEPRECATED - More info on active projects and modules at https://dat-ecosystem.org/ ] 

### Readme:
MODULE NAME


[![deprecated](http://badges.github.io/stability-badges/dist/deprecated.svg)](github.com/martinheidegger/hyper-dns) See [hashbase](github.com/martinheidegger/hyper-dns) for similar functionality. 

More info on active projects and modules at [dat-ecosystem.org](https://dat-ecosystem.org/) <img src="https://i.imgur.com/qZWlO1y.jpg" width="30" height="30" /> 

---

[![deprecated](http://badges.github.io/stability-badges/dist/deprecated.svg)](https://dat-ecosystem.org/) 

More info on active projects and modules at [dat-ecosystem.org](https://dat-ecosystem.org/) <img src="https://i.imgur.com/qZWlO1y.jpg" width="30" height="30" />
