### ISSUE TITLE
1.4.1 Transitioning org repos to Dat-ecosystem

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#13]
## `@todo`
- [x] Transitioning org repos to Dat-ecosystem
  - `@input` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from #10
  - `@input` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem) from #11
  - `@input` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive) from #11
  - [x] reach out to the dat contributors to help transitioning
  - [x] update list with new links to the repos and modules 
  - [x] transition org repos under Dat ecosystem Github
  - [x] have old domains pointing to github pages
    - [x] reach out to CS&S to link dat.foundation, dat.project, dat.land etc. to github page replacements (e.g. https://dat-ecosystem.org/dat.land/)
    - [x] add CNAME files to github pages where applicable
    - [x] reach out to CS&S to update domain A records to point to github
  - `@output` :package: [`refined list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules)
    - next #14
  - `@output` :package: [`old dat website repos`](https://github.com/dat-ecosystem)
    - next #14
  - `@output` :package: [`old dat org pages`](https://github.com/dat-ecosystem-archive)
    - next #14
  
---

## `@info`

**criteria for organisational repo:**
  - outdated documentation
  - code of conduct
  - project management repositories
  - design
  - old websites

| type        | estimation        |
| ------------ | ------------------- |
| deadline  | 2022.01.31      |
| duration   |  `4 hours`        |
| bounty     | `$320 USD`     |
| assignee  | @ninabreznik |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2022.01.31`
     * budget: `40 USD / hour`
     * duration: `8 hours`
* review:
    * date: `2022.01.25`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2022.02.13`
    * sender: @dat-ecosystem/consortium 
    * receipient: @ninabreznik 
    * amount: `320 USD`
