### ISSUE TITLE
1.4.2 Archiving Org

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#14]
## `@todo`
- [ ] add deprecation notice to org repos & web pages + link to dat ecosystem
  - `@output` :package: [`refined list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) from #13
  - `@input` :package: [`old dat website repos`](https://github.com/dat-ecosystem) from #13
  - `@input` :package: [`old dat org pages`](https://github.com/dat-ecosystem-archive) from #13
  - [x] design a deprecation notice (text & UI (simple html))
  - [x] add deprecation notice text to the repositories + link to the successor
  - [x] make all old webpages run as github pages
  - [x] add deprecation notice to old dat foundation twitter account
    - `@input` :package: [`old dat foundation twitter account`](https://twitter.com/dat_project)
    - `@output` :package: [`old dat foundation twitter account`](https://twitter.com/dat_project)
      - next #15
  - [x] inform audience in old gitter chat
    - `@output` :package: [`chat message notification`](https://gitter.im/datproject/discussions?at=61939e72cd4972068baca502)
      - next #15
  - [x] add deprecation notice to the UI
  - `@output` :package: [`updated old dat website repos`](https://github.com/dat-ecosystem)
  - `@output` :package: [`updated old dat org pages`](https://github.com/dat-ecosystem-archive)

---

## `@info`

| type        | estimation        |
| ------------ | ------------------- |
| deadline  | 2022.01.31      |
| duration   |  `24 hours`      |
| bounty     | `$960 USD`     |
| assignee  | @ninabreznik |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2022.01.31`
     * budget: `40 USD / hour`
     * duration: `24 hours`
* review:
    * date: `2022.01.25`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2022.02.13`
    * sender: @dat-ecosystem/consortium 
    * receipient: @ninabreznik 
    * amount: `960 USD`
