### ISSUE TITLE
2.1.1.1. Identify existing hypercore audience

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#15]
#8

## `@todo`
- [ ] find key projects, people, organizations related to hypercore
  - `@input` :package: [`old dat foundation twitter account`](https://twitter.com/dat_project) from #14
  - `@input` :package: [`chat message notification`](https://gitter.im/datproject/discussions?at=61939e72cd4972068baca502) from #14
  - `@input` :package: [`dat-ecosystem blog`](https://github.com/dat-ecosystem/blog) from #9
  - `@input` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/) from #9
  - `@input` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem) from #11
  - `@input` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive) from #11
  - `@input` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) #from 10
  * [x] find projects, people, organizations related to hypercore protocol and the ecosystem
  * [x] developers, projects (modules, companies..)
  * [x] financial supporters (grant programs, patrons...)
  * [x] media (tech bloggers, community newsletters
  * [x] p2p tech social media creators (youtube, tiktok, twitch), podcasts...)
  - [x] go through results of task dependencies (below)
  - [x] go through dat-ecosystem-archive modules and find dependents 
  - [x] visit old webpages (dat.foundation, dat.project, dat.land)
  - [x] scan through the blog and outgoing links
  - [x] go through the consortium mailing list
  - [x] go through dat twitter
  - [x] go through dat conference, data terra nemo and youtube talks
  - [x] go through comm comm and consortium logs
  - [x] identify friendly communities (ssb...)
  - [x] go to chats (irc+old gitter, hyper discord, dat discord)
   - [x] go through list of users
   - [x] quick search for links and key phrases in chats to identify projects and interest groups
     - [ ] e.g. ('https', 'project', 'working on', ...other keywords to find them)
  - `@output` :package: [`audience list`](https://hackmd.io/@T6Wf5EsOQKe-6wyPjJPtuw/SJIOkpIz2)
---

## estimated duration:
3 days

## estimated budget:
960 USD
