### ISSUE TITLE
2.1.3.2 Blog posts for the interview series

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#19]
## `@todo`
- [ ] create blog posts for the Dat ecosystem
  - `@input` :question: `communication plan` from #7
  - `@input` :question: `communication goals, channels & strategies` from #6
  - [ ] write blog posts for project interview introductions
  - [ ] create custom design for each blog post (using project's logo)
  - [ ] share the post
    - Twitter, Mastodon, FB (P2P group), Discord (Dat ecosystem, Hyper, Local first web dev)
    - consortium newsletter
    - ...
  - `@outputs` :question: `newsletters`
    - 10 blog posts with custom design 
---
## info
inspiration: https://redecentralize.org/redigest/2021/06/

## estimated duration:
4 days

## estimated budget:
1280

**Comment by ninabreznik** [comment]
TODO

- use consortium notes + add if any updates were posted in Discord channel (any project) + any big news from hypercore 
- we don't call it a newletter but Dat ecosystem digest (monthly digest)
- once a month for 1 year (12 x)
- check for emails with Joe Hand and/or Mauve (Mailchimp)
- send emails using Google groups or Mailchimp
