### ISSUE TITLE
2.2.1.2 Copywrite content for History section of the page

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#21]
#8

## `@todo`
- [ ] update a list of major events & add to the history template
  - `@input` :question: `communication plan` from #7
  - `@input` :question: `communication goals, channels & strategies` from #6
  - [x] copywrite content for history section
  - [x] review the history document (https://hackmd.io/cuolp56RRkmMNqr_6fIW1A)
    - link dat white paper
    - dat conferences
- [x] add content to history section of the webpage
  - `@output` :factory: [`update history json file, which auto-updates https://dat-ecosystem.org/history.html`](https://hackmd.io/cuolp56RRkmMNqr_6fIW1A?both)
    - next #23 

---

## `@info`
```
* code comments: https://github.com/dat-ecosystem/dat-ecosystem.github.io/blob/main/src/index.js#L7-L244
* hackmd: https://hackmd.io/cuolp56RRkmMNqr_6fIW1A?view
* dat foundation page https://dat.foundation/about/history/
* check all old websites and the dat-ecosystem blog for more items
* e.g.
    * https://www.youtube.com/watch?v=_Tcr2anPUc8
    * https://www.youtube.com/channel/UCbLY5Qg3t3OJbxZZUioqMOQ
    * https://web.archive.org/web/20210107084811/https://blog.datproject.org/
    * https://dat.foundation/about/history/
```

## estimated duration:
1 day

## estimated budget:
320usd

**Comment by ninabreznik** [comment]
@Frando if you are busy, I can finish this task and you take another one. I am already working on documenting all the repos and figuring out which to deprecate. Plus I already started to gather history events, so I can also just finish it.

Let me know.

**Comment by Frando** [comment]
Hi @ninabreznik – sorry for coming back this late! I indeed have a lot on my plate at the moment and did not yet find the time to actually write prose for the history section. If this is OK for you I'd be fine with you taking over this task. If not I could come back to it at the beginning of January. And in any case I can review and add things if you share a PR or HackMD  :purple_heart:

**Comment by ninabreznik** [comment]
@Frando Hey, thanks for your response. If you really don't mind, I would then just also do this history, BUT maybe we could add additional task for datrs organization - a cleanup and archiving and documenting. Would that make sense? Any ideas what would need to be done or let's say what could be done in a day or two (that's approx the budget we have for these tasks)?

**Comment by ninabreznik** [comment]
History including 2021
https://hackmd.io/cuolp56RRkmMNqr_6fIW1A?both
