### ISSUE TITLE
2.2.1.3 Copywrite content for Organizational structure & governance (consortium, manifesto, membership)

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#22]
#8

## `@todo`
- organisational structure & governance (consortium, manifesto, membership)
  - `@input` :question: `communication plan` from #7
  - `@input` :question: `communication goals, channels & strategies` from #6
  - `@input` :package: [`inspiration from discocoop`](https://disco.coop/governance-model/)
- [x] describe ALL tools/app in official use and which organizational function is solved in the dat-ecosystem by using that tool
  - e.g. jitsi, discord/cabal, twitter, github org, blog, website, ...
- [x] describe how people communicate and meet to make decisions
- [x] describe and link to manifesto, code of conduct and other official docs on github markdown files in website repo
- [x] describe any standard processes to join as a project or progress as a project through different stategs in the dat-ecosystem as a garden 
- [x] have organizing structure and processes expressed and integrated into website https://dat-ecosystem.org
- [ ] have consortium structure expressed and integrated into website https://dat-ecosystem.org
- [x] have a link to github manifesto.md added to website https://dat-ecosystem.org
- [x] show projects and members profile on website https://dat-ecosystem.org
  - `@output` :factory: [`website section for organizing structure and processes`](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png)
    - next #23 
  - `@output` :factory: [`website section to explain consortium with manifesto and members`](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png)
    - next #23

---

## estimated duration:
2 days

## estimated budget:
640 usd

**Comment by ninabreznik** [comment]
![image](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png)
