### ISSUE TITLE
2.2.1.4 Concept, design and implementation of the website

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#23]
#8 

## `@todo`
- [ ] concept, design and implementation
  - `@input` :question: `communication plan` from #7
  - `@input` :question: `communication goals, channels & strategies` from #6
  * `@input` :package: [`current dat-ecosystem website repo`](https://github.com/playproject-io/dat-ecosystem.github.io)
  * `@input` :package: [`current dat-ecosystem website: https://dat-ecosystem.org`](https://dat-ecosystem.org)
  - `@input` :package: [`dat-ecosystem organization`](https://github.com/dat-ecosystem/organization/blob/main/README.md)
  - `@input` :factory: [`usable website section for dat-ecosystem as a garden`](https://user-images.githubusercontent.com/1076427/145653389-814d54e1-148e-4e47-af38-0e34aceba2d9.png) from #20
  - `@input` :factory: [`dat-ecosystem garden application form`](https://docs.google.com/forms/d/e/1FAIpQLSf9YxzVOTdPQKTwFoHzPTpSBNEm9dqOdYnZdP_bPAy4hrGQ0A/viewform) from #20
  - `@input` :question: `usable website section for dat-ecosystem as a garden` from #20
  - `@input` :factory: [`update history json file, which auto-updates https://dat-ecosystem.org/history.html`](https://hackmd.io/cuolp56RRkmMNqr_6fIW1A?both) from #21
  - `@input` :factory: [`website section for organizing structure and processes`](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png) from #22
  - `@input` :factory: [`website section to explain consortium with manifesto and members`](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png) from #22
  - `@input` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/) from #9
  - `@input` :package: [`dat-ecosystem open collective account`](https://opencollective.com/dat)
  - `@input` :package: [`hypercore-protocol project`](http://hypercore-protocol.org/)
  - `@input` :package: [`outdated wikipedia entry`](https://en.wikipedia.org/wiki/Dat_(software))
  - `@input` :package: [`list of dat-ecosystem consortium meeting notes`](https://hackmd.io/@T6Wf5EsOQKe-6wyPjJPtuw/Hycn0F63r/%2FgjGP6PI7Q7-cTepr9QEm1w)
  - `@input` :package: [`dat-ecosystem twitter account`](https://twitter.com/dat_protocol)
  - `@input` :package: [`initial dat whitepaper`](https://github.com/dat-ecosystem-archive/whitepaper)
  - `@input` :package: [`historic community contributions`](https://github.com/dat-ecosystem-archive/awesome-dat)
  - `@input` :package: [`longer list of historic events in source code`](https://github.com/dat-ecosystem/dat-ecosystem.github.io/blob/main/src/index.js)
  - `@input` :package: [`history in the old website`](https://dat.foundation/about/history/)
  - `@input` :package: [`dat-ecosystem archive`](https://github.com/dat-ecosystem-archive)
  - `@input` :package: [`outdated old dat npm packages`](https://www.npmjs.com/org/dat-ecosystem)
  - `@input` :package: [`old datproject discussions`](https://github.com/dat-ecosystem-archive/datproject-discussions/issues)
  - `@input` :package: [`old outdated docs 1`](https://dat-ecosystem-archive.github.io/docs/)
  - `@input` :package: [`old outdated docs 2`](https://dat-ecosystem-archive.github.io/how-dat-works/)
  - `@input` :package: [`old technical standards1`](https://github.com/dat-ecosystem-archive/web-specs)
  - `@input` :package: [`old technical standards 2`](https://dat-ecosystem.org/DEPs/)
  - `@input` :package: [`old technical standards 3`](http://datprotocol.com/)
  - `@input` :package: [`old advisory committee`](https://github.com/dat-ecosystem-archive/advisory-committee)
  - `@input` :package: [`history: hypercore-protocol becomes independent`](https://github.com/dat-ecosystem-archive/governance)
  - `@input` :package: [`old outdated documentation`](https://dat-ecosystem-archive.github.io/book/)
  - `@input` :package: [`historic information about dat organisation`](https://github.com/dat-ecosystem-archive/organization)
  - `@input` :package: [`list of historic dat ecosystem projects`](https://github.com/dat-ecosystem-archive/projects)
  - `@input` :package: [`more dat ecosystem projects`](https://github.com/dat-ecosystem-archive/project-updates)
  - `@input` :package: [`old website - dat.land`](https://dat-ecosystem.org/dat.land/)
  - `@input` :package: [`old website - dat-data.com`](https://dat-ecosystem-archive.github.io/dat-data.com/)
  - `@input` :package: [`old another website`](https://dat-ecosystem-archive.github.io/old-website/)
  - `@input` :package: [`old list of upcoming events`](https://events.dat.foundation/)
  - `@input` :package: [`repo of old upcoming events listing`](https://github.com/dat-ecosystem/public-events)
  - `@input` :package: [`old newsletter`](https://github.com/dat-ecosystem/newsletter/tree/master/2019)
  - `@input` :package: [`old website - datproject.org`](https://datproject.org/)
  - `@input` :package: [`old website - dat.foundation`](http://dat.foundation/)
  - [x] make concept for the website
  - [x] pull all the pages together, write code, design, make concept => easy maintainable, one stop for all info
  - [x] design a theme for the website
    - `@input` :package: [`old web icon elements`](https://github.com/dat-ecosystem-archive/dat-elements)
    - `@input` :package: [`old blog theme`](https://github.com/dat-ecosystem-archive/dat-blog-theme-casper)
    - `@input` :package: [`old website - datproject.org`](https://datproject.org/)
    - `@input` :package: [`old styleguide`](https://dat-ecosystem-archive.github.io/design/)
    - `@input` :package: [`more old icons`](https://github.com/dat-ecosystem/dat-icons/tree/master/icons)
    * `@input` :package: [`dat colors`](https://github.com/dat-ecosystem/dat-colors)
  - [x] add content
  - [x] #37 

---

## estimated duration:
7 days

## estimated budget:
2890

**Comment by ninabreznik** [comment]
So far, we have spent:
- Nina for managing the whole thing (0 so far)
- 300 usd Mimi for first webpage draft
- todo: refine website
