### ISSUE TITLE
2.2.1.5 Projects of Dat Ecosystem Interview Series

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#24]
#8

## `@todo`
- [x] prepare interview
 - [x] `intro and outro` 
 - [x] `online video interview recorded by interviewer on Keet/Discord/Jitsi`
   - [x] send questions upfront, so interviewee can prepare tabs to screenshare (if necessary)
   - [x] make sure sound quality is amazing
   - [x] videos with add intro/outro & published to youtube`
- [x] create intro video to interiview youtube series
  - `@output` :checkered_flag: :package: [`intro video`](https://www.youtube.com/watch?v=L-TFWFfUk-0&list=PL7sG5SCUNyeYM6ib3-c_I4IiQSGgI5PaH&index=4)
- [ ] make a series of interviews with dat-ecosystem project founders
  - [x] #53
  - [x] #54
  - [x] #55
  - [x] #56
  - [x] #58 
  - [x] #59
  - [x] #60
  - [x] #61
  - [x] #62
  - [x] #63
  - [x] #64
  - [x] #65
  - [x] #66
  
---
## estimated duration:
30 hours

## estimated budget:
1400$ for the videos (100 per interview)
100$ for intro/outro
200$ for editing and publishing to Youtube

**Comment by ninabreznik** [comment]
TODO

WAIT for website design

- prepare 3 questions
- limit 3 - 5 min
- invite projects to record the 'self interview'
- use budget to make intro & outro ( Nina (Luka, Petar) or Frazee's brother)
- consortium selects videos
- publish to Youtube & blog & Twitter
-
