### ISSUE TITLE
Positioning Map for dat-ecosystem

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#25]
#115

## `@todo`
* [ ] collect information about all adjacent projects and ecosystems which are not in the dat-ecosystem
* [ ] make a concept for how to compare and position them
* [ ] create tables and/or visualizations with the ecosystem map and add it to the website or blog

---

## info
```
build on top of this work: https://hackmd.io/qVhO0vNsQle9fGFLdxOPfA
```
