### ISSUE TITLE
update broken links to forward to dat-ecosystem

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#27]
#115

## `@todo`
* [ ] update/forward domains to the transitioned dat-ecosystem blog
* [ ] collect links online and request maintainers to update to forward to dat-ecosystem
  * [ ] update [this github issue comment](https://github.com/ipfs/in-web-browsers/issues/121#issuecomment-489182127)
  * [ ] update [wikipedia entry](https://en.wikipedia.org/wiki/Dat_(software))
  
---

## `@info`
there are many places online where people still reference broken links from previous times and every time we discover them we should reach out to update those.
