### ISSUE TITLE
make manifesto based dapp for dat-ecosystem consortium

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#28]
#115

## `@todo`
* [ ] create specification from discussions and the information linked below
  * `@input` :factory: [`consortium meeting 57 - proposal`](https://hackmd.io/zFzM7_FQT8iKVawf94af7g#PROPOSAL)
  * `@input` :factory: [`multisig proposal v0.0.2`](https://hackmd.io/NT7RReeERU-lQsPOqZ3mXg)
  * [ ] create repository for the planned work
  * [ ]  collect and discuss all relevant details to create a proper concept for further todos
  * [ ] summarize it all precisely in a markdown specification file
* [ ] program the solidity smart contract(s) to implement the specification
* [ ] implement a dapp user interface to interact with the smart contract
* [ ] deploy smart contract to moonrock rococo testnet
* [ ] present to dat-ecosystem consortium for testing phase
* [ ] deploy smart contract to moonbeam polkadot parachain

---

## `@info`

**resources**
* https://docs.moonbeam.network/
* https://academy.moonbeam.network/
* https://docs.moonbeam.network/learn/platform/networks/overview/
* https://moonbeam.network/tag/testnet/
* https://moonbeam.network/announcements/moonbeam-network-testnet-now-available/

**brief description**
The main binding document at the moment are:
1. https://github.com/dat-ecosystem/organization/blob/main/MANIFESTO.md
2. https://github.com/dat-ecosystem/organization/blob/main/code-of-conduct-contact.md
3. https://github.com/dat-ecosystem/organization/blob/main/code-of-conduct.md

1. The smart contract should be deployed knowing all current consortium members pubkeys
2. Members can submit regular proposals until 48 hours before the next biweekly consortium meeting
3. Members can vote on regular proposals during consortium meetings
    * a single vote for the proposal is enough to make the proposal pass 
    * unless a single veto by a member is submitted, which is enough to reject a proposal
    * regular proposals concern strategy and operations of the dat-ecosystem consortium and spending funds
4. Members can present and submit special proposals during a consortium member
   * special proposals touch the manifesto or consortium members
   * for removing a member from the consortium it requires unanimous consensus minus one
   * for adding a member or changing the rights or rules granted by the manifesto 100% consensus is required
