### ISSUE TITLE
forward old websites and blog to new dat-ecosystem website and blog

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#29]
#115

## `@todo`
* [ ] forward https://blog.datproject.org/ to new blog
  - `@input` :package: [`dat-ecosystem blog`](https://github.com/dat-ecosystem/blog) from #9
  - `@input` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/) from #9
* [ ] add deprecation notice to old website sub pages
  * [ ] e.g. https://dat.foundation/explore/projects/
  * [ ] eg. https://docs.datproject.org/
  * [ ] e.g. broken link to [datbase.org](https://github.com/dat-ecosystem-archive/datBase)
  * [ ] e.g. broken [archives.datproject.org](https://github.com/dat-ecosystem-archive/public-archives)
  * [ ] e.g. maybe transition https://github.com/juliangruber/dat.haus if possible - consider fork
  * [ ] e.g. broken preview links for dat git book https://github.com/dat-ecosystem-archive/book
  * [ ] e.g. fix broken links in dat-land website https://dat-ecosystem-archive.github.io/dat.land/
  * [ ] e.g. update name to dat-project website https://github.com/dat-ecosystem-archive/dat.foundation

---

## `@info`
Any sub pages of old websites which don't have the deprecation notice can and are still found in google search results and a visitor won't know the new pages without the deprecation notice
