### ISSUE TITLE
manage `CS&S - Dat Ecosystem: "Moving Forward" Grant` (`$4500`)

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#32]
#8

## `@todo`
- [ ] manage CS&S - `Dat Ecosystem: "Moving Forward" Grant`
  - `@input` :package: [`Moving Forward Grant [CS&S}`](https://github.com/dat-ecosystem/organization/tree/main/2021.09.22%20%20_%20Moving%20Forward%20Grant)
  - [ ] make grant team to create, manage the review all grant tasks 
    * `@output` :factory: [`Grant Team Meeting Notes`](https://hackmd.io/jHruEs2uTQGpLqtFzJhsHA?view#Meeting-October-15th-2021)
  - [x] announce dat ecosystem relaunch grant work
    * `@output` :package: [`blog post source`](https://github.com/dat-ecosystem/blog/blob/main/posts/2021-12-21-dat-grant-ecosystem-relaunch.md)
    * `@output` :package: [`published blog post on open collective`](https://opencollective.com/dat/updates/dat-ecosystem-relaunch)
    * `@output` :package: [`published blog post on dat-ecosystem blog`](https://blog.dat-ecosystem.org/dat-ecosystem-relaunch/)
  - [x] find and assign people to work on all grant tasks
  - [ ] review grant task results and issue payments
  - [ ] report back to [`@dat-ecosystem/consortium`](https://github.com/orgs/dat-ecosystem/teams/consortium) during consortium meetings
  - [ ] update title of [this document](https://github.com/dat-ecosystem/organization/blob/main/2021.09.22%20%20_%20Moving%20Forward%20Grant/2021.07.09-20--.--.--%20_%20Grant%20Team%20Meeting%20Notes.md) with the finishing date
  - [ ] move all missing dat-ecosystem meeting notes into git repo folder that happen until grant finishes
    - `@input` :factory: [`Consortium Meeting Notes`](https://hackmd.io/@T6Wf5EsOQKe-6wyPjJPtuw/Hycn0F63r/%2FHbu0ffkwQS6KIO_97fH-Mw)
    - `@output` :question: [`Archived Consortium Meeting Notes`](https://github.com/dat-ecosystem/organization/tree/main/consortium%20meeting%20notes)

---

## `@info`
...
