### ISSUE TITLE
find and link successor modules & projects for all historic dat repos

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#33]
#115

## `@todo`
- [ ] find and link successor modules & projects for all historic dat repos
  - `@input` :package: [`old dat foundation twitter account`](https://twitter.com/dat_project) from #14
  - `@input` :package: [`chat message notification`](https://gitter.im/datproject/discussions?at=61939e72cd4972068baca502) from #14
  - `@input` :package: [`dat-ecosystem blog`](https://github.com/dat-ecosystem/blog) from #9
  - `@input` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/) from #9
  - `@input` :package: [`dat-ecosystem npm org`](https://www.npmjs.com/org/dat-ecosystem) from #11
  - `@input` :package: [`dat-ecosystem-archive repos`](https://github.com/dat-ecosystem-archive) from #11
  - `@input` :package: [`list of repos & maintainers`](https://hackmd.io/8uiDThl7S3OB-EC3JFUoqg?both#List-of-DAT-repositories-and-modules) #from 10
  - `@input` :question: `audience list` from #15
  - `@input` :question: `audience list from survey` from #16
  - [ ] update all repos to link to successor projects
  - [ ] make plan to create and support/fund new projects to cover successor projects where they dont yet exist
  - `@output` :question: list of updated repos with succesors
  - `@output` :question: list of planned repos/modules/projects to create missing successors

---

## `@info`
...
