### ISSUE TITLE
 implement and publish website

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#37]
#23 

## `@todo`
* [ ] implement and publish website
  * `@input` :package: [`identity idea`](https://github.com/dat-ecosystem/organization/blob/main/visual%20assets/concept%20by%20vasic%20media/Dat%20logo%20presentation4.pdf)
  * `@input` :package: [`website`](https://dat-ecosystem.org/)
  * [ ] improve text on the website
    * `@output` :question: `pull requests with suggested changes`    
  * [x]  create a dat-ecosystem mad scientist character
    * `@output` :package: [`dat ecosystem character artwork`](https://github.com/dat-ecosystem/organization/tree/main/visual%20assets/assets%20by%20tommings/scientist%20and%20other%20assets)
  * [x] #114
  * [ ] create custom icons for the page
     * `@output` :question: `new icons`
  * [x] create a  banner image 
    * [x] make it work for website
    * [x] make it work as a twitter banner
    * `@output` :package: [`banner image`](https://github.com/dat-ecosystem/organization/blob/main/visual%20assets/assets%20by%20tommings/scientist%20and%20other%20assets/Dat%20Ecosystem%20-%20Final%20Illustration%20-%20Scientists%20%26%20Tree%20-%202022.svg)
  * [ ] make a concept for assets integration and design improvement 
     * `@input`: :package:  [`assets`](https://github.com/dat-ecosystem/organization/tree/main/visual%20assets/assets%20by%20tommings) 
    * `output`: :question: `figma wireframe` 
  * [ ] web development stage preparations
    * `@input`: :question: `figma wireframe`  
    * [x]  watch the web development workshops
    * [x] watch Toshi's talk
    * [ ] restructure/split Dat ecosystem page into version controlled component style (v0.0.1 + later we can add more iterrations if we need to)
    * `output`: :question: [`version controlled figma wireframe`]()
  * [x] #68
  * [x] #70
  * [ ] https://github.com/dat-ecosystem/dat-ecosystem/issues/3
    - `@input` :question: `dat ecosystem github page` from https://github.com/dat-ecosystem/dat-ecosystem/issues/15
    - [ ] publish website under dat-ecosystem.org
    * `@output` :package: [`refined logotype versions`](https://github.com/dat-ecosystem/organization/tree/main/media/assets%20by%20tommings/logo) from  #114
    - `@output` :question: `artworks for the website and social media`
    - `@output` :question: `website UI/UX specification & wireframes`
    - `@output` :question: `dat-ecosystem design system`
    - `@output` :question: `list of re-usable web components`
    - `@input` :checkered_flag: :question: `dat-ecosystem.org` from `comment`

**Comment by Hornet004** [comment]
[worklog 2022.09.09  8:28PM](https://youtu.be/TiVAvxZJh3E)
[worklog 2022.09.09  8:28PM](https://youtu.be/iROJyvzQrog)
[worklog 2022.09.09  8:28PM](https://youtu.be/FvNj38qCIUE)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.10  2:12AM](https://youtu.be/IkZncddzPU0)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.11  11:52AM](https://youtu.be/SwTt5Hkx2IA)
[worklog 2022.09.11  01:04PM](https://youtu.be/fFvXEfUkpKM)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.12  12:22PM](https://youtu.be/m4Dw8tjlEVw)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.12  07:32PM](https://youtu.be/52xz-OxjFqI)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.12  08:11PM](https://youtu.be/811yR7jmsuw)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.15  11:41PM](https://youtu.be/h7k1w_idBqc)

* `doing` Figma wireframe
  * `@output`❓[Figma wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=0%3A1)

**Comment by Hornet004** [comment]
[worklog 2022.09.19  08:50PM](https://youtu.be/6bVguJ5brAA)
[worklog 2022.09.19  08:50PM](https://youtu.be/ImInGgrdx_o)
[worklog 2022.09.19  08:50PM](https://youtu.be/Qqr5rXdjfjs)
[worklog 2022.09.19  08:50PM](https://youtu.be/3i7jiCtG2MI)

[worklog 2022.09.19  08:50PM](https://youtu.be/5DicWG34QbA)

* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.09.22  09:43PM](https://youtu.be/_no-bQ5kZYU)
[worklog 2022.09.22  09:43PM](https://youtu.be/hPUi_GsuHkI)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.09.24 ](https://youtu.be/h_GqUuBuY-M)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.09.26 ](https://youtu.be/5mQBs-b4Y8o)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.01 ](https://youtu.be/SY58w8Ma0o8)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.03 ](https://youtu.be/EaEa2CmQqR4)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.09 ](https://youtu.be/bXGskpzaodU)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.12 02:07PM](https://youtu.be/Xs0S_MWd9tY)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.14 10:23PM](https://youtu.be/6YtpL9bZK4I)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
[worklog 2022.10.15 7:40AM](https://youtu.be/zhm7HFrqIng)


* `doing` Figma wireframe
  * `@output`❓[Figma final screen wireframe](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799)

**Comment by Hornet004** [comment]
## Tasks
- watch Toshi's video videos
   - View youtube content provided by Toshi ``` 2hr 8mins```
   - ```@output``` 📦 github comment from [comment](https://github.com/dat-ecosystem/organization/issues/37#issuecomment-1324228221)
- Update github comment
   - Update comment  ``` 1hr 15mins```
   - ```@output``` 📦 github comment from [comment](https://github.com/dat-ecosystem/organization/issues/37#issuecomment-1324228221)
-------------
## Feedbacks
#### There are questions in the worklog video and also I'll like to ask if we would be creating both light and dark modes components
-------------
## Worklogs
   ### [worklog-77](https://youtu.be/YcmjmnhmJC0)
-------------
## Proposals
-------------

**Comment by serapath** [comment]
**feedback `2022.11.23`**

![compoennt example](https://imgur.com/sKth1s8.png)
1. The github issue link links to the one and only worklog comment where that specific version of the component design was created/produced as an `@output`.
2. The dependencies link to the figma pages to the specific designs of the components that are used

so you understand correctly.

![popovers component](https://imgur.com/QDtLh1v.png)

You are correct, this is a mistake.
The story was, that the popovers component was a component v0.0.1
That included all these individual designs in one component, but without names and versions.

Every design was a different mode of the popovers component, similar to how
a button can be enabled and disabled and so on ...basically different states.

We then agreed to deprecate the popovers component and create individual components as successor components, each with their own name and version.

So yes - there should not be a name/version for those designs inside the content area of the popover component, instaed they should have been just names or labels for those individual states of the popover component, so please just ignore that name/version thing :-)

Sorry for the confusing, but good for pointing it out, so we can improve the video to present how we do figma versioning.
thx


![successors](https://imgur.com/10Zvt8g.png)

So if you take an existing component version design on figma and create a final "deprecated" version, but the features or functionality solved by this now outdated components are solved instead by other components that were designed, then those components should be listed.
They are essentially links to the figma page and position where those specific new "successor" components with the specified versions have been designed, so clicking the link jumps to that figma page for the specific successor component you clicked on.

A component can also have no succesor component and just be deprecated, because we decided to not use it anymore, e.g. imagine we would have created a `<marquee>` component but somehow decided to not use it anymore with no replacement ...even though, if it was used to display news, then maybe we should link to the component that we now use to display the same news? .... anyway, hope that makes it more clear.


----

## merging components

ok, so i think there is a misunderstanding.

If you have two component A and B, you can make a component C that uses A and B as dependencies ...that is NOT a "merged component".

Instead - a "merged component" is the opposite of a "split component".

So you would deprecate 2 or more components at the same time
and you link to the same new component you made which combines all the features of the two old previous components.
You then link this new combined component as the only "successor component" in both old deprecated components.

We do NOT use these old components as dependencies in the new component.
We do not use the old components anymore at all.
But if somebody still has a link to those old designs, they can now find the link to the new successor component that replaced the old components.

So the technique is the same as in the split component, but instead of having one component and many new, we have many old deprecated and one new.
Any case in between is also possible, but that is how it works.

Every time you deprecate components, you can list possible successor components that should be used from now on instead of the deprecated component.

**Comment by Hornet004** [comment]
> stead of having one component and many new, we have many old deprecated and one new.

So how do we structure the files, how do we move to know this Figma file link is going to contain deprecated files and the new Figma link would contain new design from the deprecated file {Note: there is a difference between Figma files and Figma pages} or do we say we restructure a particular page to have sub-pages containing the deprecated designs? If we say yes hence we can't publish to Figma community because of its max number of pages to be created for free users. If we don't publish it "might" work

**Comment by Hornet004** [comment]
## Tasks
- [ ] Create Figma components
   - [ ] Create and separate components to single forms ``` 11hr 9mins```
   - ```@output``` 🚋   Figma single component file from [Figma](https://www.figma.com/file/CuLgmODrFRQuQTWGWrFK3k/Dat-ecosystem?t=CgobACuIZhFjvlP3-1)
   - [ ] Create combined components and sections``` undefined```
   - ```@output``` ❓  Figma single component file from [Figma](https://www.figma.com/file/CuLgmODrFRQuQTWGWrFK3k/Dat-ecosystem?t=CgobACuIZhFjvlP3-1)
   - [ ] Update GitHub comment
   - Update comment  ``` 42mins```
   - ```@output``` 📦 GitHub comment from [comment](https://github.com/dat-ecosystem/organization/issues/37#issuecomment-1328025300)
-------------
## Feedbacks
#### Broke the components into single components then I would proceed to link them together into larger components and sections.
-------------
## Worklogs
   ### [worklog-78](https://youtu.be/cRPFVuCJVhA)
-------------
## Proposals
-------------

**Comment by ninabreznik** [comment]
## Feedback 
Nov 26th 2022

Here is my feedback on the content of your work

Part 1: https://www.loom.com/share/dcf12139efe54730b1212ec76e7a8bf9
Part2: https://www.loom.com/share/f5a1ed25d5194192a9e566df7437d5d0

Links for inspiration (code is of course not the same as these components are part of certain frameworks):
- https://material.angular.io/components/categories
- https://getbootstrap.com/2.3.2/components.html
- https://tailwindcomponents.com/

And here are some of our existing components (which might need a little bit of brushing up before use)
- https://github.com/datdot-ui
