### ISSUE TITLE
Sher - demo/review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#40]
#18

## `@todo`
 `@input`: video interview :question:
 - [x] learn about the project (if you can't find all the info online, interview the core contributors)
 - [x] record a screencast (a demo) with the author or just yourself
 - [x] write a short blog post in a markdown
  * a bit about yourself (to understand from which perspective are the interviews/demos/article)
  * short about the project ( 1 paragraph)
  * main links (website, documentation, code, community/discord etc.)
  * video interview link
  * demo screencast link
 - [ ] publish to youtube
 `@output` :question:  `A 1 page write up with the link to the video and the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by Ruulul** [comment]
Name: V
Contact: 5-142857#7577
Estimated start: Dec 2 2022
Estimated end: Dec 3 2022

**Comment by ninabreznik** [comment]
@Ruulul Looking forward to it. Any questions, please let me know :)

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/BJIYXLeg2

**Comment by KaylaOlu** [comment]
Demo
https://wormhole.app/JMq6x#6n7g4N25ItnTSKziJ68HKg

**Comment by KaylaOlu** [comment]
Demo
https://wormhole.app/PLPv4#cZP_Vz0Ye35Yu9q47PY53Q

**Comment by KaylaOlu** [comment]
Interview
https://wormhole.app/1Rrkb#718z8nCrFST6fHcQgifEUg

**Comment by KaylaOlu** [comment]
Interview
https://wormhole.app/KjOAk#XVb_bbaoLVb2nleY0aHoug
