### ISSUE TITLE
Keet - demo/ review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#41]
#18

## `@todo`
 `@input`: video interview :question:
 - [ ] learn about the project (if you can't find all the info online, interview the core contributors)
 - [ ] record a screencast (a demo) with the author or just yourself
 - [ ] write a short blog post in a markdown
  * a bit about yourself (to understand from which perspective are the interviews/demos/article)
  * short about the project ( 1 paragraph)
  * main links (website, documentation, code, community/discord etc.)
  * video interview link
  * demo screencast link
 - [ ] publish to youtube
 `@output` :question:  `A 1 page write up with the link to the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### how to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by KaylaOlu** [comment]
Name: Kayla
Contact (Twitter/Discord/Email): @Kayla_O
Estimated start: Dec 28 2022
Estimated completion: Jan 7 2023

**Comment by KaylaOlu** [comment]
Interview
https://we.tl/t-E5Wrio8W03

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/BJbfFrpO3

**Comment by KaylaOlu** [comment]
Demo
https://we.tl/t-NYKLmxQp2l
