### ISSUE TITLE
Hop - demo/ review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#43]
#18

## `@todo`
 `@input`: video interview :question:
 - [ ] learn about the project (if you can't find all the info online, interview the core contributors)
 - [ ] record a screencast (a demo) with the author or just yourself
 - [ ] write a short blog post in a markdown
  * a bit about yourself (to understand from which perspective are the interviews/demos/article)
  * short about the project ( 1 paragraph)
  * main links (website, documentation, code, community/discord etc.)
  * video interview link
  * demo screencast link
 - [ ] publish to youtube
 `@output` :question:  `A 1 page write up with the link to the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by Ruulul** [comment]
Name: V
Contact (Discord): 5-142857#7577
Estimated start: Dec 06 2022
Estimated completion: Dec 06 2022

**Comment by KaylaOlu** [comment]
Interview
https://wormhole.app/RPbAA#iIQ8Z_pvJIDTeMBzykn9PA

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/HJDj6qjeh

**Comment by KaylaOlu** [comment]
Demo
https://we.tl/t-45tTRLq8PD


Interview
https://we.tl/t-0lpQjeSFz8
