### ISSUE TITLE
Cabal - demo/ review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#45]
#18

## `@todo`
 - [ ] learn about the project (if you can't find all the info online, interview the core contributors)
 - [ ] write blog post in a markdown
  * a few words about the project (what does it do)
  * where to find the documentation
  * write the step by step instructions for anyone who would want to test it themselves too
 - [ ] record a screencast 
  * follow your instructions to  download & run the product as intended
  * record the process & comment it
 - [ ] publish to youtube
 `@output` :question:  `A 1 page write up with the link to the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```
