### ISSUE TITLE
Ahau - demo/ review

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#47]
#18 

## `@todo`
 `@input`: video interview :question:
 - [x] learn about the project (if you can't find all the info online, interview the core contributors)
 - [x] record a screencast (a demo) with the author or just yourself
 - [x] write a short blog post in a markdown
  * a bit about yourself (to understand from which perspective are the interviews/demos/article)
  * short about the project ( 1 paragraph)
  * main links (website, documentation, code, community/discord etc.)
  * video interview link
  * demo screencast link
 - [ ] publish to youtube
 `@output` :question:  `A 1 page write up with the link to the screencast` 
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by KaylaOlu** [comment]
Interview Video
https://wormhole.app/3Qk2z#L7jYmAbK29IGWaMBb_FPew

**Comment by KaylaOlu** [comment]
Demo Video
https://wormhole.app/JrDNP#312T695pa9Jc5KHI-zYjVg

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/S14T9Dnao

**Comment by ninabreznik** [comment]
Thanks, @KaylaOlu I am downloading it now.
