### ISSUE TITLE
Video interview with Cabal team

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#55]
#24

## `@todo`
 - [x] learn about the project (if you can't find all the info online, interview the core contributors)
 - [x] use the following question (customize + add subquestions when needed)
   * What is your project about?
   * Who is it for?
   * How is the project funded and what is the plan to make is sustainable?
   * What parts are open sourced and where can code repositories be found?
   * How is the project using/planning to use Hypercore protocol/p2p stuff?
   * What are the plans for the next few months/year?
   * How can one join the community/contribute to the project?
 - [x] contact the team (founders/core maintainers) and schedule the interview
 - [x] send the questions in advance so interviewee can prepare
 - [x] Make a test recording and make sure sound is perfect
 - [x] Use Sher/Discord/Keet or Jitsi for a video call and record it using Loom/Screencastify or other screen recording tools
 - [x] make sure video doesn't exceed 10min
 - [x] publish video to youtube
 `@output` :checkered_flag: :package:  [`A 5-10min video in mp4 format `](https://www.youtube.com/watch?v=5s6IaF5Q3JI&list=PL7sG5SCUNyeYM6ib3-c_I4IiQSGgI5PaH&index=5)
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by KaylaOlu** [comment]
Demo
https://we.tl/t-wD9dRyNYZF

**Comment by KaylaOlu** [comment]
Article
https://hackmd.io/@Klair/SJrU9qdm3

**Comment by KaylaOlu** [comment]
Interview
https://wormhole.app/zPjnY#w4kDRE9zF1Ull8zTN_2PhA
