### ISSUE TITLE
Video interview with Hyperpubee team

### ISSUE THREAD

**Issue by ninabreznik** [dat-ecosystem/organization#59]
#24 

## `@todo`
 - [x] learn about the project (if you can't find all the info online, interview the core contributors)
 - [x] use the following question (customize + add subquestions when needed)
   * What is your project about?
   * Who is it for?
   * How is the project funded and what is the plan to make is sustainable?
   * What parts are open sourced and where can code repositories be found?
   * How is the project using/planning to use Hypercore protocol/p2p stuff?
   * What are the plans for the next few months/year?
   * How can one join the community/contribute to the project?
 - [x] contact the team (founders/core maintainers) and schedule the interview
 - [x] send the questions in advance so interviewee can prepare
 - [x] Make a test recording and make sure sound is perfect
 - [x] Use Sher/Discord/Keet or Jitsi for a video call and record it using Loom/Screencastify or other screen recording tools
 - [x] make sure video doesn't exceed 10min
 - [x] publish video to youtube
 `@output` :movie_camera: :  `A 5-10min video in mp4 format ` https://youtu.be/boo8FraTSSE
 
 ---
### Budget: 
$100 (paid through the Open Collective after the completion and review)

### How to apply?

Comment on the selected issue with:

```
Name: Foobar
Contact (Twitter/Discord/Email): @foobar
Estimated start: Nov 20 2022
Estimated completion: Nov 30 2022
```

**Comment by KaylaOlu** [comment]
Name: Kayla
Contact (Twitter/Discord/Email): @Kayla_O
Estimated start: Jan 31 2023
Estimated completion: Feb 9 2023

**Comment by KaylaOlu** [comment]
https://wormhole.app/kKr3y#JwJ3Qb87AuPsegX-IzRhsg
