### ISSUE TITLE
Dat Ecosystem web component

### ISSUE THREAD

**Issue by Hornet004** [dat-ecosystem/organization#68]
#37 

## `@todo`
- [x] Organization
   - `@input` :package: [Task Management & Version Control playlist](https://youtube.com/playlist?list=PLFimBx2yWz_WSTH8uoiSE4dHsvVUeXsDZ) from https://github.com/wizardamigos/wizardamigos.github.io/issues/124
   - [x] Go through feedbacks work logs feedback
   - [x] meet with Toshi for a GitHub comment explanation
   - [x] Scheduled another meeting with Toshi for  GitHub comment explanation
   - [x] Create and Edit a new issue
   - [x] Create a video explanation
   - [x] Reupdate issue
   - `@output` 📦 [`New issue`](https://github.com/dat-ecosystem/organization/issues/68#issuecomment-1332748389) from [`comments`](https://github.com/dat-ecosystem/organization/issues/68#issuecomment-1332748389)
   
---
- [x] Split- Dat ecosystem page into version-controlled component style (v0.0.1)
  - `@input` 📦 [`Figma wireframe`](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799&t=61nlDe5CrCoKqvDK-1) from  #37
  - [x] Split and create an overview of how the component would look like
  - [x] Create a video explaining the overview
  - [x] Re-create git comment using the recorded video while pc tripped off
  - [x] Receive feedback and create each component
  - [x] Process feedback and create each component 
  - `@Output` 📦   `version-controlled component style (v0.0.1)` from https://github.com/dat-ecosystem/organization/issues/68#issuecomment-1336829603
 ---
- [x] building components(New task)
  - `@input` 📦 `version-controlled component style (v0.0.1)` from https://github.com/dat-ecosystem/organization/issues/68#issuecomment-1336829603
  - [x] Go through feedback and create new task - `1hr56min`
  - [x]  Build ❓  #69 
    - `@output` :package: [Icon_with_texts_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=32%3A17&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Button_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A95&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [theme_switcher_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A70&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Navbar_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A45&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [About_us_section_card_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=47%3A940&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Projects_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A137&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Footer_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A161&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Header_ card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A333&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Call_to_action_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A415&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Collaborators_tools_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A482&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [profile_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=35%3A46&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [growth_program_role_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A99&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Growthprocess_locator_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1334&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Growthprocess_overview_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1369&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Growthprocess_details_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A583&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A696&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Search_Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=49%3A1412&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Search_Input_+button_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A795&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Search_not_found_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A282&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Timeline_Card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A400&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Pagination_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=39%3A649&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Filter_tag_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A907&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [checkbox_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=56%3A1438&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [Filter_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A870&t=KeYaEMSUD0te4crd-4)
    - `@output` :package: [mobile_menu_sticky_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A355&t=KeYaEMSUD0te4crd-4)

**Comment by Hornet004** [comment]
## tasks
- Organization
   - went through feedbacks on discord feedbacks - `31min` 
   - meet with Toshi for an GitHub comment explanation - `20min`
   - Create and Edit new issue - `29min`
   - Scheduled another meeting with Toshi for GitHub comment explanation - `50min`
   - Create a video explanation and upload - `15min`
   - Reupdate issue - `30min`
      - `@output` 📦 #68
---
## feedbacks
* Read and watched all feedback from discord and still didn't understand them and had to schedule a meeting with toshi, then created a new issue
* Also updated the issue
---
## worklogs
* https://youtu.be/VUS-ohdn9o4
---
## proposals
---

**Comment by serapath** [comment]
**feedback `2022.12.02`**

thx. i edited minor things, e.g. `@Output` to `@output` and in the top level comment, i changed the input of the `Organization` task to toshi's "Task Management Playlist", because that seems more accurate than using the figma file as input, which is not really related to any of the github issue structuring.

otherwise, everything is spot on, so again thank you for pushing through - it might not seem a lot and it takes some time, but in the long run having all issues done accurately in this style is valuable for us to not get lost in details. Looking forward to the next worklog and I guess that's when @ninabreznik will mainly give feedback, because this time my job is just to make sure we are staying organized with our task management

**Comment by Hornet004** [comment]
## tasks
- Split- Dat ecosystem page into version-controlled component style (v0.0.1)
   - Split and create an overview of how the component would look like - `2h 40min` 
   - Create a video explaining the overview - `11min`
   - Re-create git comment using the recorded video while pc tripped off - `40min`
      - `@output` :package: [Figma -Dat ecosystem page into version-controlled component style](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=1%3A751&t=6wPaV8t3TckBDg3Z-1)
---
## feedbacks
* Splitted the components for an overview so Nina and I could discuss them and the direction
---
## worklogs
* https://youtu.be/fFlnPidc-2A
* https://youtu.be/2zI2AtWR19o
---
## proposals
---

**Comment by ninabreznik** [comment]
Hi, @Hornet004,

here are the feedbacks 
https://www.loom.com/share/3aabaea5e6ef44ce929d0cd3f488df9a
https://www.loom.com/share/fa2aefb31eac48f28362e0b4568dbc56

**Comment by Hornet004** [comment]
## tasks
- Split- Dat ecosystem page into version-controlled component style (v0.0.1)
   - Receive feedback and create each component - `14min` 
   - Process feedback and create each component - `10h11min`
   -  GitHub comment - `12min`

      - `@output` :package: [Icon_with_texts_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=32%3A17&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Button_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A95&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [theme_switcher_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A70&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Navbar_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A45&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [About_us_section_card_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=47%3A940&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Projects_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A137&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Footer_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A161&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Header_ card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A333&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Call_to_action_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A415&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Collaborators_tools_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A482&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [profile_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=35%3A46&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [growth_program_role_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A99&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Growthprocess_locator_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1334&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Growthprocess_overview_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1369&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Growthprocess_details_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A583&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A696&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Search_Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=49%3A1412&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Search_Input_+button_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A795&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Search_not_found_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A282&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Timeline_Card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A400&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Pagination_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=39%3A649&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Filter_tag_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A907&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [checkbox_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=56%3A1438&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [Filter_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A870&t=KeYaEMSUD0te4crd-4)
      - `@output` :package: [mobile_menu_sticky_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A355&t=KeYaEMSUD0te4crd-4)
---
## feedbacks
* Got feedback from Nina and worked on each component.
---
## worklogs

---
## proposals
---

**Comment by ninabreznik** [comment]
Looks good. As I said, we will adjust the components as we go, that is why we now have this versioning system.

So, little feedback:
- header and growth-program-card components have the component presented twice (once with the title, version and dependencies and once without, so let's remove the ones without)
- mobile popup doesn't have the title, version and dependencies

So, let's now start with the first component. maybe an icon with the text or a button?

**Comment by Hornet004** [comment]
## tasks
-  building components(New task)
   - Build ❓ https://github.com/dat-ecosystem/organization/issues/69
      - `@output` :package: [icon_with_texts_v0.0.1](https://github.com/Hornet004/Icon_with_texts_v0.0.1-)

---
## feedbacks
* built text wiht image component
---
## worklogs

---
## proposals
---
