### ISSUE TITLE
Refine dat-ecosystem website UI

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#70]
#37

## `@todo`
- [x] Go over the dat-ecosystem project and figma file

    - `@input` :package: [Icon_with_texts_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=32%3A17&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Button_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A95&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [theme_switcher_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A70&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Navbar_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A45&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [About_us_section_card_v0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=47%3A940&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Projects_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A137&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Footer_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A161&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Header_ card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A333&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Call_to_action_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A415&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Collaborators_tools_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=33%3A482&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [profile_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=35%3A46&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [growth_program_role_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A99&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Growthprocess_locator_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1334&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Growthprocess_overview_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=48%3A1369&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Growthprocess_details_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A583&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A696&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Search_Input_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=49%3A1412&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Search_Input_+button_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=40%3A795&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Search_not_found_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A282&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Timeline_Card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A400&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Pagination_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=39%3A649&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Filter_tag_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A907&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [checkbox_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=56%3A1438&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [Filter_card_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=44%3A870&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [mobile_menu_sticky_v.0.0.1](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component?node-id=37%3A355&t=KeYaEMSUD0te4crd-4) from #68
    - `@input` :package: [`dark color theme`](https://www.figma.com/file/CuLgmODrFRQuQTWGWrFK3k/Dat-Ecosystem-web-component-1?type=design&node-id=8-2828)
    - `@input` :package: [`light color theme`](https://www.figma.com/file/CuLgmODrFRQuQTWGWrFK3k/Dat-Ecosystem-web-component-1?type=design&node-id=8-2828) from #86
   - `@input` 📦 [dat_ecosystem](https://www.figma.com/file/sHZL5WXNsPyOTvLFDj5qJM/DAT-ECOSYSTEM?node-id=184%3A35799&t=bCJAPOQtvsR8MD3u-0) from #37 
   - `@input` 📦 [dat_ecosystem_web_component_1](https://www.figma.com/file/CuLgmODrFRQuQTWGWrFK3k/Dat-Ecosystem-web-component-1?node-id=8%3A2828&t=Ea7wYMdIXnMTYo4X-0) from [comment](https://github.com/dat-ecosystem/organization/issues/37#issuecomment-1328025300)
   - `@input` 📦 [dat_ecosystem_web_component_2](https://www.figma.com/file/C0PKa1LoWlBQFyfG4WXDEl/Dat-Ecosystem-web-component-2?node-id=32%3A17&t=9Q81kwFCLQiT2yVZ-0) from [comment](https://github.com/dat-ecosystem/organization/issues/68#issuecomment-1336829603)
   - [x] Create an issue and structure tasks
   - [x] Duplicate Figma files
   - [x] merge `web component 1`, `web component 2` and website files (so all components can be linked separately)
   - `@output` 📦 [dat_ecosystem_website](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/DAT-ECOSYSTEM?node-id=184%3A35799&t=JcsogkWGPvDEX3xN-1) from [comment](https://github.com/dat-ecosystem/organization/issues/70#issuecomment-1374936345)

---

- [x] Improve home screen
   - `@input` 📦 [dat_ecosystem_website](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/DAT-ECOSYSTEM?node-id=184%3A35799&t=JcsogkWGPvDEX3xN-1)
   - [x] look for references
      - [x] provide mood board
      - `@output` 📦 [moodboard_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/DAT-ECOSYSTEM?node-id=634%3A9087) from [comment](https://github.com/dat-ecosystem/organization/issues/70#issuecomment-1376304801)
   - [x] update the `homepage` based on the feedback
   - `@output` 📦 [homepage_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=647%3A4661&t=CNXdnCH6xrxUBIFl-4) from [comment](https://github.com/dat-ecosystem/organization/issues/70#issuecomment-1377714784)

---

- [x] Improve homepage_v0.0.2
   - [x] go over the feedback- `34min`
   - [x] update the `homepage` based on the feedback - `1h58min`
   - [x] record worklog and update tasks - `23min`
   - `@output` 📦 [homepage_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=664%3A2791&t=CNXdnCH6xrxUBIFl-4) from [comment](https://github.com/dat-ecosystem/organization/issues/70#issuecomment-1383178763)
- [x] add dark theme of homepage - `3min`
   - `@input` 📦 [homepage_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=664%3A2791&t=CNXdnCH6xrxUBIFl-4)
   - [x] update the `homepage` to dark theme
   - `@output` 📦 [homepage_dark_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=665%3A3387&t=CNXdnCH6xrxUBIFl-4) from [comment](https://github.com/dat-ecosystem/organization/issues/70#issuecomment-1383178763)

---

- [x] Separate the current design into the following components
   - `@input` 📦 [homepage_dark_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=665%3A3387&t=CNXdnCH6xrxUBIFl-4)
   - [x] #71 
   - [x] #72 
   - [x] #73 
   - [x] #74 
   - [x] #75 
   - [x] #76 
   - [x] #77 
   - [x] #78 
   - [x] #79 
   - [x] #80 
   - [x] #81 
   - [x] #82 
   - [x] #83 
   - [x] #84 
   - [x] #85 
   - [x] #86 
   - [x] #87 
   - [x] #89 
   - [x] #90 
   - [x] #91 
   - [x] #92 
   - [x] #93 
   - [x] #94 
   - [x] #95 
   - [x] #96 
   - [x] #97 
   - [x] #98 
   - [x] #99 
   - [x] #102 
   - [x] #104 
   - [x] #105 
   - [x] #108 
   - [x] #112

**Comment by Mehrabbruno** [comment]
# tasks

- Go over the dat-ecosystem project and figma file - `27min`
   - Create an issue and structure tasks - `22min`
   - Duplicate Figma files - `5min`
   - merge `web component 1`, `web component 2` and website files (so all components can be linked separately) - `38min`
   - record worklog, update task and comments - `18min`
   - `@output` 📦 [dat_ecosystem_website](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/DAT-ECOSYSTEM?node-id=184%3A35799&t=JcsogkWGPvDEX3xN-1)

---

# worklog

[worklog - 98](https://youtu.be/TwXR1PtLcGM)

---

# feedback

- I went over the previous tasks and figma files
- Created a different issue and task

---

# proposals

- [ ] create a mood board for the design changes. (aim for bringing more vibrancy to the whole website)

**Comment by serapath** [comment]
**feedback `2022.01.09`**

I saw your bloobies and choo chew designs.
The dat ecosystem colors are pretty much fixed.
they are green, pink, darkblue, black and white - it has been like this more or less since 2013 and cant be changed.
of course in images with characters there need to be some more and maybe different colors, but the page in general has to be in the main dat colors.
here is a link to an older page that has those main colors https://datproject.org/

Here are the main pages of the dat-ecosystem for comparison - they are basically just black and white
https://cabal.chat/
https://www.datprotocol.com/  (old page)
here the former main page of the protocol https://web.archive.org/web/20211203060652/https://hypercore-protocol.org/
https://peermaps.org/
here is yet another partner project https://earthstar-project.org/
here is ours https://datdot.org/


So just keep in mind, that this is the environment which things are coming from - deeply minimalistic, simplistic and mostly black/white.
People do live in the computer terminal, where they stare into a shell and see one message after another in a console, issuing commands and it's mostly using some system mono fonts.

Now our page should match that, but for sure we have to get away from corporate! That is really  bad that it resembles corporate.
Despite the characters and images, the page should look technical.

For example, here is the internet engineering task force that write many or even most of the standards that make up the internet
https://www.rfc-editor.org/rfc/rfc7693

here is another page that is frequented by people in the community https://tildeverse.org/ or https://tilde.club/
many are fans of old retro computers, like the commodore64 and the likes

If we can make the page look very technical, maybe like a terminal with ascii characters and system mono fonts and the likes and confine the art into specific regions or areas where they fit and integrate nicely, that would be sweet.

**Comment by Mehrabbruno** [comment]
## Tasks

- look for references  - `41min`
   - provide mood board
   - record worklog and update tasks - `21min`
   - `@output` 📦 [moodboard_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/DAT-ECOSYSTEM?node-id=634%3A9087)

---

## Worklog

[worklog-100](https://youtu.be/0x3rXgwrYYo)
[worklog-101](https://youtu.be/7MPg-6BF1Z4)

---

## Feedback

---

## Proposals

**Comment by Mehrabbruno** [comment]
## Tasks

- Improve home screen
   - go over `2022.01.09` feedback - `26min`
   - update the `homepage` based on the feedback - `2h53min`
   - record worklog and update tasks - `21min`
   - `@output` 📦 [homepage_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=647%3A4661&t=CNXdnCH6xrxUBIFl-4)

---

## Worklog

[worklog-102](https://youtu.be/XW8DwoiMvYg)

---

## Feedback

- Kindly ignore the fact that I only linked the single frame and now the correct version on. I will be updating it tomorrow. was just busy and had to go somewhere

---

## Proposals

**Comment by Mehrabbruno** [comment]
## Tasks

- Improve home screen
   - go over the feedback- `34min`
   - update the `homepage` based on the feedback - `1h58min`
   - record worklog and update tasks - `23min`
   - `@output` 📦 [homepage_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=664%3A2791&t=EDWA1B0Dkvmgsovo-4)
- add dark theme of homepage_v0.0.3 - `3min`
   - update the `homepage` to dark theme
   - `@output` 📦 [homepage_dark_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=762%3A4248&t=EDWA1B0Dkvmgsovo-4)

---

## Worklog

[worklog-103](https://youtu.be/OxBRNCwv-cU)

---

## Feedback

---

## Proposals

**Comment by serapath** [comment]
**feedback `2023.01.16`**

---

### coding

Lets do the changes mentioned below, but then please also break down the project into some components you think are useful. The design affacts mostly the "Front page", but the menu shows we have some sub pages, for each we have the content already in the current page.
So we need them all and if there are a few components you are pretty sure can stay, maybe you can put them into "figma version controlled components" so we can on the side also start implementing those :-)


---

### page content

You are right - the old page was tech/protocol/product oriented.
The new page is projects oriented - it's now an ecosystem and the tech/protocols/products can be found with each project instead of dat-ecosystem directly.

Here is the current website and the information is on that page https://dat-ecosystem.org/
The way it is structured can be improved and if you read through the old pages (at least titles and sub titles) maybe some ideas could be used to refine things, but the main content is the one on the current website.

In essence - The content is important, but if you have suggestions of how to make things more minimal and concise (e.g. moving some content to other sections, etc...), let me know or maybe even suggest in the next figma wireframes

So again, for content, check the latest page https://dat-ecosystem.org

---

### dat projects

The changes are otherwise nice.
Still - projects will be classified and based on whether it is a new student or side project by a solo dev or a mature componay with users and a fully fledged product, we give it a badge, which is the logo with a leaf that grows to full size or it is empty with not even a seed in it and every stage in between, see
https://github.com/dat-ecosystem/organization/tree/main/visual%20assets/assets%20by%20tommings/logo

---

### banner and theme/style/colors

Also - yes, retro the way you started the design is great.
The core projects i shared with you have a very minimalistic design,
much simpler than the old "dat pages" and mostly just black and white with a system mono font

By the way, the main picture of the tree should probably be the one that has the project logos in the tree leafs. check twtter banner to see what i mean.
https://twitter.com/dat_ecosystem


It has to be close to previous designs in terms of colors or specific recognizable elements, so somebody who hasn't checked **dat** for the last 3-4 years, will recognize elements and figure out they are still looking at or dealing with the same things that they discovered back then. I don't think the soft shadow white boxes are part of that, so we can skip those.

I still think we need to re-use the banner somewhere in some form
https://web.archive.org/web/20201001002406/https://datbase.org/ has it and many other old pages have it too.

It is cool that you changed the square in the header to a hexagon.
The small hexagons around look nice, but might take a bit from the retro feel - or not? what do you think? ...maybe they can animate, sounds cool.

**old blinking cursor:**
This is actually a feature we want to support for real, not initially but later.
Maybe a "real" terminal that shows some sort of [welcome message](https://www.google.com/search?q=terminal+welcome&tbm=isch&ved=2ahUKEwjmsuLq98r8AhX2UKQEHY8MCsoQ2-cCegQIABAA&oq=terminal+welcome&gs_lcp=CgNpbWcQAzIFCAAQgAQyBggAEAgQHjIGCAAQCBAeMgcIABCABBAYOgQIABBDOggIABCABBCxAzoGCAAQBRAeUJUEWLsKYMMLaABwAHgAgAGBAogBrwiSAQUyLjIuM5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=DqjEY-bzI_ahkdUPj5mo0Aw&bih=1134&biw=1095) because we later want to allow a user to type `.help` to actually see some options and then interact with the page through the terminal for real - but we wont have that in the initial implementation now.
I didn't want to mention it, but now that you bring up the cursor, i thought i share it :-) 

Also, the dark purple though is the color from the characters hair but is not a traditional dat color, so we should keep the green i think. What i mean by re-using elements from old websites is more literally re-using them and not figuratively or in the same spirit, but literally re-using some so that they are recognizable. Not all of them, **but if you go through the pages - like in the video - and you see all those pages: What are the re-occuring symbols and elements?** We should take the most iconic and defining ones.

Maybe in the history/timeline section, we can also have a list of **all the previous logos**?
clicking one might even jump to a specific point in the timeline :-)

here is a [direct link to the banner](https://web.archive.org/web/20200315163802/https://datbase.org/public/img/bg-landing-page.svg)

It can be framed in a box, like a screen/display or whatever.
It could be part of the footer.
But keep in mind that **dat-ecosystem** was inactive for probably around 2 years, so most people are only used to those old pages and they all are quite similar, while the new one significantly changes style and colors. So this will still tell people they are dealing with the same project, but evolved.

**Also:** That banner captures all important colors:
green/pink/white/black ...only the "dark blue" is missing.

The red and light blue aren't that important are just in the pallette of the other colors that were once in use or are useful in special situations.

The square footer seems better than the previous footer hexagon, but mainly because the footer hexagon had rounded corners which to me made the whole feel different - maybe if it had shard edges like the new hexagon banner frame in the header, it would be fine too, who knows.

Also: the discord icon is one chat and the `cabal` is another chat, so maybe it should have another icon? currently it looks like the title or name for the discord icon.
Cabal logo is also one dat-ecosystem project and has a downward arrow, see: https://cabal.chat/


---

### structure

It is probably not possible to have all pages without any scrolling - wish it was possible.
Anyway, just keep in mind, that the projects page currently has those cards, but we need space or a placeholder for the 3D supply chain network that is in the making.
Probably it just needs to be framed, like a display/screen? somewhere? maybe like an old gaming console style? i have no idea. Anyway something like this
https://vasturiano.github.io/3d-force-graph/example/large-graph/
