### ISSUE TITLE
dat-ecosystem website_buttons

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#71]
#70

## `@todo`

- [x] design the following buttons for dat-ecosystem website with different states
   - [x] deprecate `primary_button_v0.0.1` and `secondary_button_v0.0.2`
   - [x] design shadow light-theme 
   - [x] design shadow dark-theme
   - [x] design normal
   - [x] design icon 
   - [x] design trailing icon 
   - [x] text button
   - [x] create and update tasks, worklog, comment etc
   - `@output` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4) from [comment](https://github.com/dat-ecosystem/organization/issues/71#issuecomment-1398159775)

---

- [x] update the button_v0.0.1
   - `@input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4)
   - [x] make the buttons flat and retro design
   - [x] link the buttons properly
   - [x] create and update tasks, worklog etc
   - `@output` 📦 [`buttons_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1374-6906&t=Ox51Ohm1m5cMB0nq-4) from [comment](https://github.com/dat-ecosystem/organization/issues/71#issuecomment-1500657565)
     - next #72 
     - next https://github.com/dat-ecosystem/dat-ecosystem/issues/1

**Comment by Mehrabbruno** [comment]
### tasks

- design the following buttons for dat-ecosystem website with different states - `1h22min`
   - deprecate primary_button_v0.0.1 and secondary_button_v0.0.2
   - design shadow light-theme
   - design shadow dark-theme
   - design normal
   - design icon
   - design trailing icon
   - text button
   - create and update tasks, worklog, comment etc - `17min`
   - @output 📦 [buttons_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4)

---

## worklog 

[worklog-104](https://youtu.be/P8KYnirQVHM)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2022.01.20`**

checked also the figma and the components.
It seems checking top to bottom, components have been wireframed until `image_tree_...` which is not yet implemented and neither all components following it.

I also noticed, that the `"Web UI"` does not yet include a version that utilizes the old pages main iconic elements so people would feel some familiarity despite the new design (one such element would be that colored hexagon grids banner used in several old pages)

also i havent seen yet the project card component versions with the growing leaf in the logo to indicate the stage/phase of each project the way we planned and hence chose the new logo for.

lastly - the current website dat-ecosystem.org and davids design have designed **all** pages while so far with the new design i only see the first page or rather the projects (but no placeholder yet for the graph visualization i mentioned)

That is all i noticed - but maybe you made issues for those to plan already or plan to do so?

Lastly - if there are any news of progress from the ppl you found to work on the datdot component wireframes, that would be lovely to hear too :-)

**Comment by Mehrabbruno** [comment]
### tasks - `2023.04.08`

- update the button_v0.0.1 - `18min`
   - make the buttons flat and retro design
   - link the buttons properly - `6mni`
   - create and update tasks, worklog etc  - `18min`
   - `@output` 📦 [`buttons_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1374-6906&t=Ox51Ohm1m5cMB0nq-4)

---

## worklog 

[worklog-131](https://youtu.be/BDx_oaC_XfY)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.04.09`**

great. buttons are cool. nice and retro.

please kep all components properly linked even if it takes some extra time to update dependencies and dependents.

And yes, even in terminal and elsewhere, everything will be a standalone component, **but wait for making those atomic mini components until the end**
Basically when we agree everything is DONE and we move to implementation, then we can make those final components.
