### ISSUE TITLE
dat-ecosystem website_navbar

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#72]
#70

## `todo`

- [x] Design light and dark theme navbars
   - `input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4) from #71 
   - [x] create and update tasks, worklog, comment etc
   - [x] add company logo
   - [x] add text buttons for pages links
      - [x] home page
      - [x] projects
      - [x] growth program
      - [x] consortium
      - [x] timeline
   - [x] add icon buttons for 
     - [x] discord icon
     - [x] github icon
     - [x] twitter icon
     - [x] switching the theme color from dark and light
  - `@output` 📦 [`navbar_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=733%3A17512&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1398857911)

---

- [x] update the navbar_v0.0.2
   - `@input` 📦 [`navbar_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=733%3A17512&t=98H6hlGXYrdj950w-4)
   - `@input` 📦 [`terminal_buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=850%3A7269&t=YNst1ZTI5axnR4pA-4) from #87 
   - [x] make the navbar bevel and put inside the terminal frame
   - [x] add and update tasks
   - `@output` 📦 [`navbar_v0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=850%3A6739&t=YNst1ZTI5axnR4pA-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1402790849)

---

- [x] update the navbar_v0.0.3
   - `@input` 📦 [`navbar_v0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=850%3A6739&t=YNst1ZTI5axnR4pA-4)
   - [x] remove social btns from navbar to a social container
   - `@output` 📦 [`navbar_v0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1102%3A2508&t=2eJNNRFFInrn2WRG-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1451025056)

---

- [x] update the navbar_v0.0.4
   - `@input` 📦 [`navbar_v0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1102%3A2508&t=2eJNNRFFInrn2WRG-4)
   - [x] add a terminal btn
   - [x] add a socials toggle btn
   - `@output` 📦 [`navbar_v0.0.5`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1103%3A2663&t=2eJNNRFFInrn2WRG-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1451025056)

---

- [x] update the navbar_v0.0.5
   - `@input` 📦 [`navbar_v0.0.5`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1103%3A2663&t=2eJNNRFFInrn2WRG-4)
   - [x] add back all the social btn icons
   - `@output` 📦 [`navbar_v0.0.6`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1156%3A2757&t=2eJNNRFFInrn2WRG-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1451025056)

---

- [x] update the navbar_v0.0.6
   - `@input` 📦 [`navbar_v0.0.6`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1156%3A2757&t=2eJNNRFFInrn2WRG-4)
   - [x] change the consortium page btn to an `i` (info) icon
   - `@output` 📦 [`navbar_v0.0.7`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1266-1911&t=If4neK4QfpiquEnl-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1478298359)

---

- [x] update the navbar_v0.0.7
   - `@input` 📦 [`navbar_v0.0.7`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1266-1911&t=If4neK4QfpiquEnl-4)
   - [x] move the `i` (info) icon to a suitable position
   - `@output` 📦 [`navbar_v0.0.8`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1316-6019&t=oHWrNNsurk7EuHVg-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1487844212)

---

- [x] update the navbar_v0.0.8
   - `@input` 📦 [`navbar_v0.0.8`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1316-6019&t=oHWrNNsurk7EuHVg-4)
   - [x] make the UI flat and retro
   - [x] read feedback
   - `@output` 📦 [`navbar_v0.0.9`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-2323&t=X986IDEOWju1Nxgs-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1500737725)

---

- [x] update the navbar_v0.0.9
   - `@input` 📦 [`navbar_v0.0.9`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-2323&t=Ox51Ohm1m5cMB0nq-4)
   - [x] move the consortium page Icons to left
   - [x] update tasks and worklogs
   - `@output` 📦 [`navbar_v0.0.10`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-3678&t=Ox51Ohm1m5cMB0nq-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1500737725)

---

- [x] update the navbar_v0.0.10
   - `@input` 📦 [`navbar_v0.0.10`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-3678&t=Ox51Ohm1m5cMB0nq-4)
   - [x] change the highlight colors
   - [x] change the discord icon position
   - [x] update tasks and worklogs
   - `@output` 📦 [`navbar_v0.0.11`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1432-2185&t=idhOGERipmYR9EQg-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1508306881)

---

- [x] update the navbar_v0.0.11
   - `@input` 📦 [`navbar_v0.0.11`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1432-2185&t=idhOGERipmYR9EQg-4)
   - [x] change the logo size
   - [x] update tasks and worklogs
   - `@output` 📦 [`navbar_v0.0.12`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1529-1911&t=mOIaKkssbiRF2cWj-4) from [comment](https://github.com/dat-ecosystem/organization/issues/72#issuecomment-1511379453)

**Comment by Mehrabbruno** [comment]
### tasks

- Design light and dark theme navbars - `8min`
   - create and update tasks, worklog, comment etc - `9min`
   - add company logo
   - add text buttons for pages links
      - home page
      - projects
      - growth program
      - consortium
      - timeline
   - add icon buttons for 
     - discord icon
     - GitHub icon
     - twitter icon
     - switching the theme color from dark and light
     - `@output` 📦 [`navbar_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=733%3A17512&t=98H6hlGXYrdj950w-4)

---

### worklog

---

### feedback

---

### proposal

**Comment by Mehrabbruno** [comment]
### tasks

- update the navbar_v0.0.2
   - make the navbar bevel and put inside the terminal frame - `13min`
   - add and update tasks - `4min`
   - `@output` 📦 [navbar_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=850%3A6739&t=YNst1ZTI5axnR4pA-4)

---

### worklog

---

### feedback

---

### proposal

**Comment by Mehrabbruno** [comment]
### Tasks

- update the navbar_v0.0.3
   - remove social btns from navbar to a social container
   - @output 📦 [navbar_v0.0.4](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1102%3A2508&t=2eJNNRFFInrn2WRG-4)

---

- update the navbar_v0.0.4
   - add a terminal btn
   - add a socials toggle btn
   - @output 📦 [navbar_v0.0.5](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1103%3A2663&t=2eJNNRFFInrn2WRG-4)

---

- update the navbar_v0.0.5
   - add back all the social btn icons - `16min`
   - create and update tasks - `15min`
   - @output 📦 [navbar_v0.0.6](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1156%3A2757&t=2eJNNRFFInrn2WRG-4)

---

### Worklog

[worklog-117](https://youtu.be/Iek_wA_ZWZM)

---


### Feedback

---

### Proposals

**Comment by Mehrabbruno** [comment]
### Tasks

- update the navbar_v0.0.6
   - change the consortium page btn to an `i` (info) icon - `17min`
   - create and update tasks - `6min`
   - @output 📦 [navbar_v0.0.7](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1266-1911&t=If4neK4QfpiquEnl-4)

---

### Worklog

[worklog-123](https://youtu.be/nVh8JEKHtbw)

---


### Feedback

---

### Proposals

**Comment by Mehrabbruno** [comment]
### Tasks - `2023.03.29`

- update the navbar_v0.0.7
   - cmove the `i` (info) icon to a suitable position - `13min`
   - create and update tasks - `4min`
   - @output 📦 [navbar_v0.0.8](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1316-6019&t=oHWrNNsurk7EuHVg-4)

---

### Worklog

[worklog-125](https://youtu.be/jYZ8dfopn9w)

---


### Feedback

---

### Proposals

**Comment by serapath** [comment]
**feedback `2023.03.29`**

Pretty good the way it is.
I adjusted the bar a bit to see what grouping makes the most sense and we decided to drop **cabal chat** again for now, because the idea is that we will make that work embedded in the website itself at some point and until then we have one icon less.

Basically all social media (discord/github/twitter) is all non-p2p and we will drop it in the future, the rest will stay.

![menubar](https://i.imgur.com/eLsWl1Y.png)

**Comment by Mehrabbruno** [comment]
### Tasks - `2023.04.08`

- update the navbar_v0.0.8 - `27min`
   - make the UI flat and retro
   - read feedback - `2min`
   - `@output` 📦 [navbar_v0.0.9](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-2323&t=X986IDEOWju1Nxgs-4)
- update the navbar_v0.0.9
   - move the consortium page Icons to left
   - update tasks and worklogs - `14min`
   - `@output` 📦 [navbar_v0.0.10](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1359-3678&t=Ox51Ohm1m5cMB0nq-4)

---

### Worklog

[worklog-128](https://youtu.be/6BLPoOTuZBw)

---


### Feedback

---

### Proposals

**Comment by serapath** [comment]
**feedback `2023.04.9`**

First it was a shock to see the monitor gone. It was nice.
But after some time of thinking i think i agree, it looks cleaner, so that is great.
Regarding the icon order, i think `discord` should be moved at the end of the socials.

Regarding the themes, it would be cool to have one with a lot of green, but the default theme should be one where we use the well know dat dark blue so people can recognize and understand that dat is now retro, but everything else still stays the same.

![navgar](https://imgur.com/iVmG0aD.png)

**Comment by Mehrabbruno** [comment]
### Tasks - `2023.04.14`

- update the navbar_v0.0.10 - `9min`
   - read feedback - `1min`
   - change the highlight colors
   - change the discord icon position
   - update tasks and worklogs - `13min`
   - `@output` 📦 [navbar_v0.0.11](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1432-2185&t=idhOGERipmYR9EQg-4)

---

### Worklog

[worklog-132](https://youtu.be/Y53KRwfx2dw)

---


### Feedback

---

### Proposals

**Comment by Mehrabbruno** [comment]
### Tasks - `2023.04.17`

- update the navbar_v0.0.11 - `5min`
   - change the logo size
   - update tasks and worklogs - `5min`
   - `@output` 📦 [navbar_v0.0.12](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1529-1911&t=mOIaKkssbiRF2cWj-4)

---

### Worklog

[worklog-135](https://youtu.be/GTTTRQ5hGvE)

---


### Feedback

---

### Proposals

**Comment by serapath** [comment]
**feedback `2023.04.17`**

+1 perfect changes. for the navbar, i think it is great now.
+1 for making the dat logo larger.

I wonder still, if we can make one theme were green is the dominant color.
maybe all buttons should be green?
but turn pink when a user highlights/focuses one?

But otherwise. awesome job, thx :-)
