### ISSUE TITLE
dat-ecosystem website_pill_tag

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#73]
#70

## `todo`

- [x] Design light and dark theme `pill_tag`
   - `input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4) from #71 
   - [x] create and update tasks, worklog, comment etc
   - [x] create tags with no fill only borders of 1px & 12px font-size
  - `@output` 📦 [`pill_tag_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2369&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/73#issuecomment-1398867677)
  - next #74

**Comment by Mehrabbruno** [comment]
### todo

- Design light and dark theme `pill_tag` - `9min`
   - create and update tasks, worklog, comment etc - `7min`
   - create tags with no fill only borders of 1px & 12px font-size
  - `@output` 📦 [`pill_tag_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2369&t=98H6hlGXYrdj950w-4)

--- 

### worklog

---

### feedback

---

### proposals
