### ISSUE TITLE
dat-ecosystem website_projects_cards

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#74]
#70

## `todo`

- [x] Design light and dark theme of projects_card
   - `input` 📦 [pill_tag_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2369&t=98H6hlGXYrdj950w-4) from #73 
   - `input` 📦 [buttons_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4) from #71 
   - [x] create and update tasks, worklog, comment etc
   - [x] add project logo
   - [x] add badge to show project status
   - [x] add social icons of the project
   - [x] add project description
   - [x] add pill tags with relative labels
  - `@output` 📦 [`projects_card_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2483&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/74#issuecomment-1398876608)

---

- [x] update projects_card_v.0.0.2
   - `@input` 📦 [`projects_card_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2483&t=98H6hlGXYrdj950w-4)
   - add badges to show project status
   - `@output` 📦 [`projects_card_v.0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=744%3A2307&t=YNst1ZTI5axnR4pA-4) from [comment](https://github.com/dat-ecosystem/organization/issues/74#issuecomment-1402808072)

---

- [x] update projects_card_v.0.0.3
   - `@input` 📦 [`projects_card_v.0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=744%3A2307&t=YNst1ZTI5axnR4pA-4)
   - update the badge placement
   - make the cover paper like wrapper
   - create and update tasks
   - `@output` 📦 [`projects_card_v.0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A13099&t=YNst1ZTI5axnR4pA-4) from [comment](https://github.com/dat-ecosystem/organization/issues/74#issuecomment-1402808072)

**Comment by Mehrabbruno** [comment]
### tasks

- Design light and dark theme of projects_card - `18min`
   - create and update tasks, worklog, comment etc - `7min`
   - add project logo
   - add badge to show project status
   - add social icons of the project
   - add project description
   - add pill tags with relative labels
   - `@output` 📦 [projects_card_v.0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=719%3A2483&t=98H6hlGXYrdj950w-4)

---

### worklog

---

### feedback

---

### proposals

**Comment by Mehrabbruno** [comment]
### tasks

- update projects_card_v.0.0.2
   - add badges to show project status
   - `@output` 📦 [projects_card_v.0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=744%3A2307&t=YNst1ZTI5axnR4pA-4)
- update projects_card_v.0.0.3 - `26min`
   - update the badge placement
   - make the cover paper like wrapper
   - create and update tasks - `6min`
   - `@output` 📦 [projects_card_v.0.0.4](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A13099&t=YNst1ZTI5axnR4pA-4)

---

### worklog

---

### feedback

---

### proposals
