### ISSUE TITLE
dat-ecosystem website_footer

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#75]
#70

## `todo`

- [x] Design light and dark theme of footers
   - `input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=tK7L4cbfl0XdCKnF-4) from #71 
   - [x] create and update tasks, worklog, comment etc
   - [x] add the Image_Robot_5
   - [x] add title of "Interested in Joining  Dat ecosystem chat network?"
   - [x] add description
   - [x] add the hexagon_1 image
   - [x] add icon buttons of
      - [x] discord icon
   - [x] add text button of
      - [x] cabal
  - `@output` 📦 [`footer_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=718%3A1911&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/75#issuecomment-1398921787)

---

- [x] Update `footer_v0.0.2`
   - `@input` :package: ['footer_v.0.0.2'](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=718%3A1911&t=98H6hlGXYrdj950w-4)
   - [x] Replace the cabal text button with cable icon btn
  - `@output` 📦 [`footer_v.0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=760%3A2725&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/75#issuecomment-1398921787)

**Comment by Mehrabbruno** [comment]
### tasks

- Design light and dark theme of footers - `20min`
   - create and update tasks, worklog, comment etc - `11min`
   - add the Image_Robot_5
   - add title of "Interested in Joining  Dat ecosystem chat network?"
   - add description
   - add the hexagon_1 image
   - add icon buttons of
      - discord icon
      - add text button of cabal
   - `@output` 📦 [footer_v.0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=718%3A1911&t=98H6hlGXYrdj950w-4)
- Update footer_v0.0.2 - `12min` 
   - Replace the cabal text button with cable icon btn
   - `@output` 📦 [footer_v.0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=760%3A2725&t=98H6hlGXYrdj950w-4)


---

### worklog

---

### feedback

---

### proposals
