### ISSUE TITLE
dat-ecosystem website_image_cover_1

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#76]
#70

## `todo`

- [x] Design light and dark theme of cover image_1
   - [x] create and update tasks, worklog, comment etc
   - [x] design the cover image using the character assets available 
   - [x] add hexagon shapes around the image
  - `@output` 📦 [`image_cover_1_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3567&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/76#issuecomment-1398941212)
- [x] update image_cover_1_v0.0.1
   - `@input` 📦 [`image_cover_1_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3567&t=98H6hlGXYrdj950w-4)
   - [x] remove the extra objects from the filled svg cover image apart from characters and tree
   - [x] replace the current image with the one with project logos 
   - `@output` 📦 [`image_cover_1_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3657&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/76#issuecomment-1398941212)
- [x] update image_cover_1_v0.0.2
   - `@input` 📦 [`image_cover_1_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3657&t=98H6hlGXYrdj950w-4)
   - [x] turn the current image to completely flat retro design
   - `@output` 📦 [`image_cover_1_v.0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A10814&t=YNst1ZTI5axnR4pA-4) from [comment](https://github.com/dat-ecosystem/organization/issues/76#issuecomment-1402785108)

**Comment by Mehrabbruno** [comment]
### todo

- Design light and dark theme of cover image_1 - `9min`
   - create and update tasks, worklog, comment etc - `6min`
   - design the cover image using the character assets available
   - add hexagon shapes around the image
   - `@output` 📦 [image_cover_1_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3567&t=98H6hlGXYrdj950w-4)
- update image_cover_v_v0.0.1 - `4min`
   - remove the extra objects from the filled svg cover image apart from characters and tree - `26min`
   - add the project logos in place of the current logo
   - `@output` 📦 [`image_cover_1_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=724%3A3657&t=98H6hlGXYrdj950w-4)

--- 

### worklog

---

### feedback

---

### proposals

**Comment by Mehrabbruno** [comment]
### todo

- update image_cover_1_v0.0.2
   - turn the current image to completely flat retro design - `36min`
   - add and update the task - `5min`
   - `@output` 📦 [image_cover_1_v.0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A10814&t=YNst1ZTI5axnR4pA-4)

--- 

### worklog

---

### feedback

---

### proposals
