### ISSUE TITLE
dat-ecosystem website_about_us_cover

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#77]
#70

## `todo`

- [x] Design light and dark theme of about_us_cover
   - [x] create and update tasks, worklog, comment etc
   - [x] add the robot character and background objects in the cover
   - [x] add the 'About Us' title
  - `@output` 📦 [`about_us_section_cover_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=723%3A2791&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/77#issuecomment-1398973066)
- [x] update the about_us_section_cover_v0.0.1
   - `@input` 📦 [`about_us_section_cover_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=723%3A2791&t=98H6hlGXYrdj950w-4)
   - move the current cover in a flat container
   - `@output` 📦 [`about_us_section_cover_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A12563&t=YNst1ZTI5axnR4pA-4) from [comment](https://github.com/dat-ecosystem/organization/issues/77#issuecomment-1402787498)

**Comment by Mehrabbruno** [comment]
### todo

- [x] Design light and dark theme of about_us_cover - `4min`
   - [x] create and update tasks, worklog, comment etc - `4min`
   - [x] add the robot character and background objects in the cover
   - [x] add the 'About Us' title
  - `@output` 📦 [`about_us_section_cover_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=723%3A2791&t=98H6hlGXYrdj950w-4)

--- 

### worklog

---

### feedback

---

### proposals

**Comment by Mehrabbruno** [comment]
### todo

- update the about_us_section_cover_v0.0.1
   - move the current cover in a flat container - `24min`
   - add and update tasks - `4min`
   - `@output` 📦 [about_us_section_cover_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A12563&t=YNst1ZTI5axnR4pA-4)

--- 

### worklog

---

### feedback

---

### proposals
