### ISSUE TITLE
dat-ecosystem website_logo

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#78]
#70

## `todo`

- [x] Design light and dark theme of website logos
   - [x] create and update tasks, worklog, comment etc
   - [x] add the designed company logo
   - [x] add the company name
      - [x] make the 'Dot' and 'Ecosystem' text color toggle between green and blue on different themes
  - `@output` 📦 [`logo_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=708%3A2068&t=98H6hlGXYrdj950w-4) from [comment](https://github.com/dat-ecosystem/organization/issues/78#issuecomment-1398977919)

**Comment by Mehrabbruno** [comment]
### todo

- Design light and dark theme of website logos - `7min`
   - create and update tasks, worklog, comment etc - `10min`
   - add the designed company logo
   - add the company name
      - make the 'Dot' and 'Ecosystem' text color toggle between green and blue on different themes
   - @output 📦 [`logo_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=708%3A2068&t=98H6hlGXYrdj950w-4)

--- 

### worklog

---

### feedback

---

### proposals
