### ISSUE TITLE
CS&S “Moving Forward” Dat Ecosystem Grant

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#8]
## `@todo`
- [ ] #32
- [x] **[Transition & archiving (`$2.240`)](https://github.com/dat-ecosystem/organization/projects/1)**
  - [x] #9   
  - [x] #10
  - [x] #11
  - [x] #12 
  - [x] #13
  - [x] #14
- [ ] **[Communication & Engagement (`$6.160`)](https://github.com/dat-ecosystem/organization/projects/2)**
  - [x] #15
  - [x] #16
  - [x] #17
  - [x] *#6*
  - [x] *#7*
  - [x] #18
  - [x] #19
  - [x] #24
- [x] **[Community hub / webpage (`$3.520`)](https://github.com/dat-ecosystem/organization/projects/3)**
  - [x] #20
  - [x] #21
  - [x] #22
  - [x] #23
---

## `@info`

# CS&S - Dat Ecosystem: "Moving Forward" Grant

### Vision
Improving society with decentralized tech.

### Mission
Our mision is to foster the decentralized *garden* by supporting initiatives and projects that have a clear positive social impact, such as civic tech, marginalized communities and science. 

We do this by promoting P2P technologies which are:

<details>
<summary>
<b>Improving society: civic tech, supporting marginalized communities and science</b>
</summary>
We believe technology should accomplish a goal that benefits humanity. At the begginning, Dat was around making easier to share and collaborate with big datasets. This was helpful for science projects.  
We'd like to keep the original dat project motivation, helping science. But we don't want to stop there, we also like to see more projects on civic tech, marginalized communities and anything that can improve society in general. Our commitment here is to help and prioritize those projects.
</details>

<details>
<summary>
<b>Consent based access control</b>
</summary>
By using private and public keys you can manage to define your own privacy level and at the same time easily share data with others.
- local/offline first
- data ownership/souvereignity
</details>

<details>
<summary>
<b>Ease of use</b>
</summary>
Through (hyper) modular design the basic blocks are easy to understand (at least on the big picture) and use to build your own project. 
</details>

#### How We Achieve Our Mission
- **Help New Projects Start**. We prepare and share knowledge in form of blog posts, open discussions or even small code repos.
- **Support Existing Projects**. From discussing and sharing technical insight to help us each other looking for, writing and applying to grant proposals.
- **Mentorships**. The main idea is to share knowledge and experiences. We plan to continue creating, not only technical content but also sharing grant's tips and even product development expertise.

**Comment by serapath** [comment]
**worklog `2022.04.24`**
* updated all tasks to new project managaement style with inputs and outputs
* prepared website task to be started
