### ISSUE TITLE
dat-ecosystem website_Image_Robot_3

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#81]
#70

## `todo`

- [x] Design light and dark theme of projects_card
   - `@input` 📦 [`Image_Robot_1_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=616%3A5877&t=Uqbfqss8UN5aBI15-4) from #79 
   - [x] create and update tasks, worklog, comment etc
   - [x] move the image_robot_3 to a figma version controlled component
  - `@output` 📦 [`Image_Robot_3_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=708%3A2717&t=Uqbfqss8UN5aBI15-4) from [comment](https://github.com/dat-ecosystem/organization/issues/81#issuecomment-1399253970)
  - next #74

**Comment by Mehrabbruno** [comment]
### tasks

- Design light and dark theme of projects_card - `3min`
   - create and update tasks, worklog, comment etc - `3min`
   - move the image_robot_3 to a figma version controlled component
   - `@output` 📦 [Image_Robot_3_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=708%3A2717&t=Uqbfqss8UN5aBI15-4)

---

### worklog

---

### feedback

---

### proposals
