### ISSUE TITLE
dat-ecosystem website_Image_Robot_5

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#83]
#70

## `todo`

- [x] Design light and dark theme of projects_card
   - `@input` 📦 [`Image_Robot_1_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=616%3A5877&t=Uqbfqss8UN5aBI15-4) from #79 
   - [x] create and update tasks, worklog, comment etc
   - [x] remove the fill from image_robot_1.
  - `@output` 📦 [`Image_Robot_5_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=710%3A3138&t=Uqbfqss8UN5aBI15-4) from [comment]()
  - next #74

**Comment by Mehrabbruno** [comment]
### tasks

- Design light and dark theme of projects_card - `3min`
   - create and update tasks, worklog, comment etc - `3min`
   - remove the fill from image_robot_1.
   - `@output` 📦 [Image_Robot_5_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=710%3A3138&t=Uqbfqss8UN5aBI15-4)

---

### worklog

---

### feedback

---

### proposals
