### ISSUE TITLE
dat-ecosystem website_original_banner

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#84]
#70

## `todo`

- [x] Move the original banner to figma component
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`original_banner_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=789%3A2024&t=EDWA1B0Dkvmgsovo-4) from [comment](https://github.com/dat-ecosystem/organization/issues/84#issuecomment-1399327910)
- [x] Update the original_banner_v0.0.1 container
   - `@input` 📦 [`original_banner_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=789%3A2024&t=EDWA1B0Dkvmgsovo-4) 
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`original_banner_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=940%3A2070&t=YAjl5us7XogR87I0-4) from [comment](https://github.com/dat-ecosystem/organization/issues/84#issuecomment-1410823146)

**Comment by Mehrabbruno** [comment]
### tasks

- Move the original banner to figma component - `17min`
   - create and update tasks, worklog, comment etc - `4min`
   - `@output` 📦 [original_banner_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=789%3A2024&t=EDWA1B0Dkvmgsovo-4)

---

### worklog

---

### feedback

---

### proposals

**Comment by Mehrabbruno** [comment]
### tasks

- Update the original_banner_v0.0.1 container - `11min`
   - create and update tasks, worklog, comment etc - `3min`
  - `@output` 📦 [`original_banner_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=940%3A2070&t=YAjl5us7XogR87I0-4)
---

### worklog

---

### feedback

---

### proposals
