### ISSUE TITLE
dat-ecosystem website_filter_options

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#89]
#70

## `todo`

- [x] Move the filter options to figma component
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`filter_options_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=942%3A2350&t=YAjl5us7XogR87I0-4) from [comment](https://github.com/dat-ecosystem/organization/issues/89#issuecomment-1410871048)

---

- [x] update filter_options_v.0.0.1
   - `@output` 📦 [`filter_options_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=942%3A2350&t=YAjl5us7XogR87I0-4)
   - [x] add the select date filter
   - [x] add search input
   - [x] add date grid
   - [x] make the up retro
   - [x] create and update tasks, worklogs, etc
   - `@output` 📦 [`filter_options_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1374-6403&t=Ox51Ohm1m5cMB0nq-4) from [comment](https://github.com/dat-ecosystem/organization/issues/89#issuecomment-1500715301)

**Comment by Mehrabbruno** [comment]
### tasks

- Move the filter options to figma component - `7min`
   - create and update tasks, worklog, comment etc - `3min`
   - `@output` 📦 [`filter_options_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=942%3A2350&t=YAjl5us7XogR87I0-4)

---

### worklog

---

### feedback

---

### proposals

**Comment by Mehrabbruno** [comment]
### tasks  -  `2023.04.08`

- update filter_options_v.0.0.1  - `12min`
   - add the select date filter
   - add search input
   - add date grid
   - make the up retro
   - create and update tasks, worklogs, etc - `8min`
   - `@output` 📦 [`filter_options_v.0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1374-6403&t=Ox51Ohm1m5cMB0nq-4)

---

### worklog

[worklog-130](https://youtu.be/shiRLUOZobA)

---

### feedback

---

### proposals
