### ISSUE TITLE
1.1 - Dat-ecosystem blog setup

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/organization#9]
## `@todo`
- [x] migrate old blog from Ghost to Github pages
  - `@input` :package: [`old blog`](https://blog.datproject.org/)
  - [x] migration of the content
  - [x] make blog work as a Github page (not ghost)
  - [x] add all blog posts under `/posts`
  - [x] use a static or dynamic page template engine (e.g. eleventy)
  - [x] connect the new blog to dat-ecosystem domain (domain/blog)
  - `@output` :package: [`dat-ecosystem blog`](https://github.com/dat-ecosystem/blog)
    - next #29
    - next #23
    - next #15
    - next #16
  - `@output` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/)
    - next #29
    - next #23
    - next #15
    - next #16

---

## `@info`

| type        | estimation                |
| ------------ | -------------------------- |
| deadline  | 2021.10.31              |
| duration   |  `8 hours`                |
| bounty     | `$320 USD`             |
| assignee  | @martinheidegger  |

**changelog**
* init:
     * from: `2021.10.01`
     * until: `2021.10.31`
     * budget: `40 USD / hour`
     * duration: `8 hours`
* review:
    * date: `2021.10.21`
    * reviewer: @dat-ecosystem/consortium 
    * status: **ok**
* payment:
    * date: `2021.10.22`
    * sender: @dat-ecosystem/consortium 
    * receipient: @martinheidegger 
    * amount: `320 USD`
    * info: @martinheidegger donated `320 USD` back to @dat-ecosystem/consortium

**Comment by serapath** [comment]
> @martinheidegger 
**worklog `2021.10.15`**
  * `@output` :package: [`dat-ecosystem blog`](https://github.com/dat-ecosystem/blog)
  * `@output` :package: [`dat-ecosystem blog github repo`](https://blog.dat-ecosystem.org/)
