### ISSUE TITLE
dat-ecosystem website_team_member_container

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#95]
#70

## `todo`

- [x] Move the team_member_container to figma component
   - `@input` 📦 [image_robot_4_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=708%3A2957&t=YAjl5us7XogR87I0-4) from #82 
   - [x] add image_robot_4_v0.0.1 for team picture
   - [x] add member name
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`team_member_container_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=953%3A3560&t=YAjl5us7XogR87I0-4) from [comment](https://github.com/dat-ecosystem/organization/issues/95#issuecomment-1411133009)

**Comment by Mehrabbruno** [comment]
### tasks

- Move the team_member_container to figma component  - `3min`
   - add image_robot_4_v0.0.1 for team picture
   - add member name
   - create and update tasks, worklog, comment etc - `3min`
   - `@output` 📦 [team_member_container_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=953%3A3560&t=YAjl5us7XogR87I0-4)
---

### worklog

---

### feedback

---

### proposals
