### ISSUE TITLE
dat-ecosystem website_pagination

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#97]
#70

## `todo`

- [x] Move the pagination to figma component
   - `@input` 📦 [`buttons_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037) from #71 
   - [x] add `icon` and `number` buttons to show pagination status
   - [x] create and update tasks, worklog, comment etc
  - `@output` 📦 [`pagination_v.0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=953%3A3693&t=YAjl5us7XogR87I0-4) from [comment](https://github.com/dat-ecosystem/organization/issues/97#issuecomment-1411138450)

**Comment by Mehrabbruno** [comment]
### tasks

- Move the pagination to figma component    - `4min`
   - add `icon` and `number` buttons to show pagination status
   - create and update tasks, worklog, comment etc - `3min`
   - `@output` 📦 [pagination_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=953%3A3693&t=YAjl5us7XogR87I0-4)
---

### worklog

---

### feedback

---

### proposals
