### ISSUE TITLE
dat-ecosystem website_project_page

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#98]
#70

## `todo`

- [x] update the projects_page_web_v0.0.1
   - `@input` 📦 [buttons_v0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=699%3A2037&t=6scFJTQQ47juqWeg-4) #71 
   - `@input` 📦 [original_banner_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=940%3A2070&t=YAjl5us7XogR87I0-4) from #84 
   - `@input` 📦 [filter_options_v.0.0.1](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=942%3A2350&t=YAjl5us7XogR87I0-4) from #89
   - `@input` 📦 [projects_card_v.0.0.4](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A13099&t=YNst1ZTI5axnR4pA-4) from #74 
   - `@input` 📦 [footer_v0.0.3](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=762%3A3795&t=6scFJTQQ47juqWeg-4) from #75 
   - `@input` 📦 [terminal_frame_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=861%3A8448&t=YNst1ZTI5axnR4pA-4) from #86 
   - [x] add the terminal frame
   - [x] add original banner with
      - [x] title of 'Our Project'
      - [x] desc of 'Our Projects in 3D, It doesnt get better than this youno :)'
   - [x] add filter options
   - [x] add project cards
   - [x] add a section for `Join our growth program`
   - [x] add `Apply now` btn
   - [x] add a footer
   - [x] add tasks, record videos etc
   - [x] make sure all the component, pages etc are linked properly
   - `@output` 📦 [`projects_page_web_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=878%3A13787&t=YAjl5us7XogR87I0-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1411198235)

---

- [x] update the projects_page_web_v0.0.2 
   - `@input`📦 [`projects_page_web_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=878%3A13787&t=YAjl5us7XogR87I0-4) 
   - [x] update the ui to new retro design
   - [x] update the tasks and worklogs
   - `@output` 📦 [`projects_page_web_v0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1448-7663&t=idhOGERipmYR9EQg-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1508366123)

---

- [x] update the projects_page_web_v0.0.3
   - `@input` 📦 [`projects_page_web_v0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1448-7663&t=idhOGERipmYR9EQg-4)
   - [x] update UI and containers
   - [x] update the tasks and worklogs
   - `@output` 📦 [`projects_page_web_v0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1532-3789&t=mOIaKkssbiRF2cWj-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1511341246)

---

- [x] update the projects_page_web_v0.0.4
   - `@input` 📦 [`projects_page_web_v0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1532-3789&t=mOIaKkssbiRF2cWj-4)
   - [x] update UI using a 30x30px grid
   - `@output` 📦 [`projects_page_web_v0.0.5`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1576-4605&t=qoY3bLfg7c6Re1yG-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1518552029)

---

- [x] update the projects_page_web_v0.0.5
   - `@input` 📦 [`projects_page_web_v0.0.5`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1576-4605&t=qoY3bLfg7c6Re1yG-4)
   - [x] add gap between project cards
   - [x] add full screen and webXR logo on the project visualization window
   - [x] change the window title to `the dat`
   - `@output` 📦 [`projects_page_web_v0.0.6`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1687-2601&t=pcDCnXs0ODDw9ms6-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1540400875)

---

- [x] update the projects_page_web_v0.0.6
   - `@input` 📦 [`projects_page_web_v0.0.6`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1687-2601&t=pcDCnXs0ODDw9ms6-4)
   - [x] read feedback
   - [x] make a icon for project visualization window
   - [x] change webXR icon
   - [x] add window close button
   - `@output` 📦 [`projects_page_web_v0.0.7`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1764-3566&t=i9jWdxjECWAyb6ri-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/98#issuecomment-1548930471)

**Comment by Mehrabbruno** [comment]
### tasks

- update the projects_page_web_v0.0.1 
   - add the terminal frame
   - add original banner with - `37min`
      - title of 'Our Project'
      - desc of 'Our Projects in 3D, It doesnt get better than this youno :)'
   - add filter options - `17min`
   - add project cards - `4min`
   - add a section for Join our growth program - `23min`
   - add Apply now btn - `2min`
   - add a footer - `2min`
   - update to dark theme - `10min`
   - add tasks, record videos etc - `23min`
   - make sure all the component, pages etc are linked properly - `36min`
   - `@output` 📦 [`projects_page_web_v0.0.2`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=878%3A13787&t=YAjl5us7XogR87I0-4)
---

### worklog

[worklog-109](https://youtu.be/Q6qrLdym_10)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2023.02.01`**

[original banner used in this page](https://datproject.org/)
Can we use the original unaltered banner with no text in the header box?
The only change would be to add project logos into some of the hexagons-  just randomly sprinkled across those hexagons, with no text.

---

What is also missing is the text present on the current website, see
https://dat-ecosystem.org/index.html

![text](https://i.imgur.com/H7zulA9.png)

---

The 3D visualization is or should be a toggle button between the project view now and the alternative 3D project view. Over time - when the 3D project view gets really good, we might as well replace the old view and just keep the card design to show information about the projects selected in the 3D graph visualization.

Not to forget that the screen should have a fullscreen and webXR mode button next to it.
I shared some pinterest links for inspiration.


---

The search/filter/status bar is great.
But when it comes to `type` i would say `tags`? maybe... and make it a dropdown to select on or more tags that projects can be tagged with to filer through them. There is no single project type.
![pic](https://imgur.com/lCP7DE1.png)

**Comment by Mehrabbruno** [comment]
### tasks `2023.04.14`

- update the projects_page_web_v0.0.2 - `15min`
   - update the ui to new retro design
   - update the tasks and worklogs
   - create, update tasks and worklog - `13min`
   - `@output` 📦 [`project_page_web_v0.0.3`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1448-7663&t=idhOGERipmYR9EQg-4)

---

### worklog

[worklog 133](https://youtu.be/sTaht5fVMaE)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2023.04.14`**

all feedback, if any, was given [here](https://github.com/dat-ecosystem/organization/issues/85#issuecomment-1509276091)

**Comment by Mehrabbruno** [comment]
### tasks `2023.04.17`

- update the projects_page_web_v0.0.3 - `12min`
   - update UI and containers
   - update the tasks and worklogs
   - create, update tasks and worklog - `14min`
   - `@output` 📦 [`project_page_web_v0.0.4`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1532-3789&t=mOIaKkssbiRF2cWj-4)

---

### worklog

[worklog 136](https://youtu.be/CKOyvhR1Vso)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2024.04.17`**

+1 brilliant, only thing ...if we have looooots of projects, how do i scroll?
if it is endless scrolling, a user might never see or reach the footer.

Basically, can you make a version that includes so many projects that it needs scrolling, just to see how that is meant to work?

I like the search/filter bar on the bottom otherwise :-)

if the projects window was a program, a user could double click the window bar to make it full screen or keep it in place. Maybe a user could technically even "close" the footer to make it go away (doesn't have an `x` at the moment).

If the projects were a program and scrollable and the footer wasnt visible on the main screen, e.g. like on mobile, then we probably would need 2 scrollbars.
- one for the page
- one for the projects inside the projects viewer program

Lastly - cool, much better without the project banner, but just to keep in mind the project visualization need to be there with options to go full screen and webXR mode too if a device supports it
![projectvis](https://imgur.com/pLdH2xI.png)

**Comment by Mehrabbruno** [comment]
### tasks `2023.04.22`

- update the projects_page_web_v0.0.4 - `31min`
   - read feedback - `2min`
   - update UI using a 30x30px grid
   - create, update tasks and worklog - `5min`
   - `@output` 📦 [projects_page_web_v0.0.5](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1576-4605&t=qoY3bLfg7c6Re1yG-4)

---

### worklog

[worklog 138](https://youtu.be/dyz1N8L9NEc)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2024.04.22`**

wow, stunning.
1. the visualization looks great - window bar should probably say `the dat` though.
2. and the project cards, should probably be inside a program window with gap between cards, just like on the homepage/landing page (basically a bit like the windows on the consortium page, so the entire window has space around, but also within the cards could have some spacing. If we lower the grid slots from `30x30` to `20x20` or maybe even `10x10` we have also more options to sometimes use the `10px` but if thats too little, then multiple times `10` for example. Basically the lowest grid size should be the size of a single letter in the font used to write the project description :-)

Also - as already mentioned on the homepage feedback - the window bar should probably include an `x` to close a section, but again, we need some way of allowing the user to re-open it through some sort of standardize mechanism or place in in the UI if you have any ideas for that.

**Comment by Mehrabbruno** [comment]
### tasks `2023.05.09`

- update the projects_page_web_v0.0.5 - `38min`
   - read feedback - `5min`
   - add gap between project cards
   - add full screen and webXR logo on the project visualization window
   - change the window title to `the dat`
   - create, update tasks and worklog - `14min`
   - `@output` 📦 [`projects_page_web_v0.0.6`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1687-2601&t=pcDCnXs0ODDw9ms6-4)

---

### worklog

[worklog 141](https://youtu.be/G2pH681Kd1k)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2013.05.10`**

nice job.
same as on home page though the individual window sections aren't closable and then "re-openable" if needed/wanted, like any other "program window"

Also again - if we had an even smaller basic grid slot size, we could make the margin around windows, the gap in the grid of project cards and/or scroll bars even smaller, maybe half the size ...or leave them as is by keeping them at least 2 slot sizes high and wide.
When you show a gap of 10px instead of 20px it didn't look all that bad to be honest.
You even show 5px which is even better, but in the end it all depends on what kind of pixelated/retro mono spaced font we find that automatically works well with a grid also when it line breaks.

If it leads to as you say: "space on the right, you could either make cards bigger, expand them by a slot size or maybe make the overall program window that contains all the cards smaller, by chaning the margin around the window, maybe it doesn't even have to be "symmetric" ...might change also in special ways when we make it responseive which will be it's own challenge :-)

Either way, the 5px slot size for gaps looks quite neat to me to be honest.
![gaps](https://imgur.com/tRVywvS.png)

So e.g. a user can close the "project list" to get more space for "THE DAT" visualization.
Also until you said it, i didn't even recognize the WebXR Logo, so maybe we need a different icon, checkout https://www.flaticon.com/free-icons/virtual-reality
Let's find something, even if it is as simple as https://help.sketchfab.com/hc/en-us/articles/204777439-Virtual-Reality-VR?page=3
![projects](https://imgur.com/OAaYmyr.png)

**Comment by Mehrabbruno** [comment]
### tasks `2023.05.16`

- update the projects_page_web_v0.0.6 - `46min`
   - read feedback - `6min`
   - make a icon for project visualization window
   - change webXR icon
   - add window close button
   - create, update tasks and worklog - `13min`
   - `@output` 📦  [projects_page_web_v0.0.7](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1764-3566&t=i9jWdxjECWAyb6ri-4)

---

### worklog

[worklog 144](https://youtu.be/7UoZvALKPEY)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2015.05.16`**

+1 for the "THE DAT" icon. awesome improvement. thanks.
+1 for the webXR mode icon. the glasses are better.

Last time you shared a few words that convinced me the entire navbar as such should have:
1. an option to make the entire website fullscreen
  * can you remove fullscreen icon from "THE DAT"? (users can dblclck window bar for it)
  * can you move the fullscreen icon into the navbar after theme icon?
2. and we also need two more "socials"
  * matrix chat https://commons.wikimedia.org/wiki/File:Matrix_icon.svg
  * mastodon account https://www.iconbolt.com/iconsets/remix-icon-fill/mastodon
  

### regarding close icon
Still same issue,when a user closes a window, we now need the "launcher".

Initially I thought of the navbar items as named "desktops", but after your last feedback, I thought of the navbar icons as "apps" as you described. Still, the "info" tab feels like a pinned browser tab and it still shows a desktop, hence I'd say the navbar items are apps, but desktop is also a special kind of app.

Giving windows on `home`, `projects`, `timeline`, `garden` a closing `x` icon makes them desktops, but not giving them that closing icon makes them some sort of special curated wall.
Both seems fine to me.

Do you prefer the desktop, because you added the `x`?

Even though we do not yet have a fully featured real desktop, we should aim for giving user that impression and one way of doing it, is the "launcher".

1. on a desktop, once a window is closed,it needs to be possible to open it again.
2. the navbar itself should also have an option to re-open or open new navbar tabs and also close them.

maybe the `dat logo` itself can be a dropdown menu to list and start programs
Maybe we can do it in the following way:
1. prefix navbar tab with program icon
2. postfix navbar tab with a `+` the user can click to open/add new programs to the desktop

The `+` button after the text in each navbar tab shows a dropdown menu from which a user can select actions for that program. In the case of a desktop, action means to launch a new program for example :-)
